fieldLayouts:
  12aee44f-6a97-442b-913a-6c6d8eda32e6:
    tabs:
      -
        fields:
          5df92654-19a4-446e-a578-2b359d4bc88f:
            required: false
            sortOrder: 1
          840f8f48-be42-4008-ae9e-1fa132183769:
            required: false
            sortOrder: 3
          f4f743d8-8e66-4bb5-920a-01bd366d6ba2:
            required: false
            sortOrder: 2
        name: Taskbooks
        sortOrder: 1
      -
        fields:
          54ffd21d-f058-4546-b582-9f8c03da2f65:
            required: false
            sortOrder: 1
        name: Membership
        sortOrder: 2
      -
        fields:
          b18328e8-46a5-482e-b83f-2ccfba7d2f20:
            required: false
            sortOrder: 1
        name: Dashboard
        sortOrder: 3
handle: globalsHtml
name: 'HTML Content'
