fieldLayouts:
  106ab0fa-af71-4120-9080-283772fe2850:
    tabs:
      -
        fields:
          4a4bc5cd-115e-4309-a51a-3e5095ceea90:
            required: false
            sortOrder: 6
          bfce8aaa-028f-4d73-8f1d-20ba8f5a871b:
            required: false
            sortOrder: 9
        name: Content
        sortOrder: 1
handle: globalsTheme
name: Theme
