fieldLayouts:
  12aee44f-6a97-442b-913a-6c6d8eda32e6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5df92654-19a4-446e-a578-2b359d4bc88f # Taskbook Page Create
            instructions: 'Shown when users are purchasing/selecting a new taskbook.'
            label: 'Taskbook Create'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b3f56002-7b2b-4b7e-a494-5e1802753108
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f4f743d8-8e66-4bb5-920a-01bd366d6ba2 # Taskbook Page Current
            instructions: 'Shown above the table of users taskbooks.'
            label: 'Taskbook Current '
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d6244072-bc7d-4e12-9409-f21835b3ce87
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 840f8f48-be42-4008-ae9e-1fa132183769 # Taskbook Page New
            instructions: 'Shown above unpaid taskbooks and PayPal button.'
            label: 'Taskbook New'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7c94642d-215c-4f7a-8bad-20a2b8389176
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 340df041-c315-4178-b695-9e98e8581d7d # Taskbook Page New Disabled
            instructions: 'Shown if new taskbooks is disabled in Lantra Skills+ settings.'
            label: 'Taskbook New (disabled)'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 51eec974-d92e-4b84-b3fa-8773b28fdd26
            userCondition: null
            warning: null
            width: 100
        name: Taskbooks
        uid: 81e9875a-ab09-42ee-8da3-5abf4aaa0bcb
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 54ffd21d-f058-4546-b582-9f8c03da2f65 # Page Membership
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2ae8ecda-ea09-45ea-b850-ba5d94e379f8
            userCondition: null
            warning: null
            width: 100
        name: Membership
        uid: 87ed8666-0a75-477e-8f99-4b8dcb84ecd1
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b18328e8-46a5-482e-b83f-2ccfba7d2f20 # Page Dashboard
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a36033a-edd8-416d-86b9-e86840bd94f9
            userCondition: null
            warning: null
            width: 100
        name: Dashboard
        uid: b7c2463b-62fe-49d9-b676-e564dc9f528c
        userCondition: null
handle: globalsHtml
name: 'HTML Content'
sortOrder: 1
