fieldLayouts:
  f71897b4-6cf6-4f45-8e13-f66ef25ca81d:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: data
hasUrls: false
name: Data
settings:
  path: '@assetsPath/data'
sortOrder: 3
titleTranslationKeyFormat: null
titleTranslationMethod: site
type: craft\volumes\Local
url: ''
