fieldLayouts:
  fca154a7-a974-4d88-a0ff-1ffb6dc8f31d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: de398320-7916-478a-994d-31c1b5944bca
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a8434c37-aebf-49bb-ae98-8b0cc29c578c
        userCondition: null
fs: data
handle: data
name: Data
sortOrder: 3
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
