fieldLayouts:
  fca154a7-a974-4d88-a0ff-1ffb6dc8f31d:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fs: data
handle: data
hasUrls: false
name: Data
sortOrder: 3
titleTranslationKeyFormat: null
titleTranslationMethod: site
url: null
