fieldLayouts:
  da87f16e-7e4f-45e6-b9cc-b4b001697ec9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: b6dfdfe0-4a3e-4bc6-a1ac-520f0c5b4f42
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f51a9edb-1159-4aec-8bd8-c6f4e909bcd9
        userCondition: null
fs: photos
handle: photos
name: Photos
sortOrder: 5
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
