fieldLayouts:
  9c411037-d675-44ab-a9aa-351919640682:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 364e633e-e00b-47a8-a29d-c335fef78aa6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d8907f76-9cf4-4b93-a515-ed517b87bbb4
        userCondition: null
fs: theme
handle: theme
name: Theme
sortOrder: 4
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
