#!/bin/bash

# remote server ips
DEV_IP="10.1.4.4"
UAT_IP="10.1.4.5"
STG_IP="10.1.4.7"
PRODUCTION_IP=""

# repo branches to sync
DEV_BRANCH="develop"
STG_BRANCH="staging"
UAT_BRANCH="uat"
PRODUCTION_BRANCH="master"

# get branch name from ref head
if ! [ -t 0 ]; then
  read -a ref
fi

IFS='/' read -ra REF <<< "${ref[2]}"
BRANCH="${REF[2]}"

# make tmp dir
TMP_DIR="/git/tmp/$BRANCH"
mkdir -p $TMP_DIR

# checkout repo to temp directory
git --work-tree=$TMP_DIR --git-dir="/git/cpd.git" checkout -f $BRANCH

# set remote server ip
if [ "$DEV_BRANCH" == "$BRANCH" ]; then
  REMOTE_IP="$DEV_IP"
elif [ "$STG_BRANCH" == "$BRANCH" ]; then
  REMOTE_IP="$STG_IP"
elif [ "$UAT_BRANCH" == "$BRANCH" ]; then
  REMOTE_IP="$UAT_IP"
elif [ "$PRODUCTION_BRANCH" == "$BRANCH" ]; then
  REMOTE_IP="$PRODUCTION_IP"
fi

# make sure we have an ip then sync the individual domains
if [ -n "$REMOTE_IP" ]; then

    # loop through domains and copy to server
    for DOMAIN in bics cha iopf ltp poultrypassport ptr ;
    do
        REMOTE_FOLDER="git@$REMOTE_IP:/datadisk/sites/$DOMAIN"

        rsync -rt -v --exclude '.gitignore' --exclude 'src' --exclude 'craft/storage/runtime' $TMP_DIR/ $REMOTE_FOLDER

        echo "lantra cpd deploy "$BRANCH" > "$DOMAIN
   done

fi

# remove temp files
rm -rf "$TMP_DIR"
