#!/bin/bash

# get branch name from ref head
if ! [ -t 0 ]; then
  read -a ref
fi

IFS='/' read -ra REF <<< "${ref[2]}"
BRANCH="${REF[2]}"

# call lantra script /home/git/bin/lantra
if [ "$BRANCH" == "develop" ]; then
  lantra dev tag
  lantra dev all
elif [ "$BRANCH" == "uat" ]; then
  lantra uat tag
  lantra uat all
elif [ "$BRANCH" == "master" ]; then
  lantra prod tag
fi