#!/bin/bash

# remote server ips
DEV_IP="51.140.230.33"
STG_IP=""
UAT_IP=""
PRODUCTION_IP=""

# repo branches to sync
DEV_BRANCH="dev"
STG_BRANCH="stg"
UAT_BRANCH="uat"
PRODUCTION_BRANCH="production"

# get branch name from ref head
if ! [ -t 0 ]; then
  read -a ref
fi

IFS='/' read -ra REF <<< "${ref[2]}"
BRANCH="${REF[2]}"

# make tmp dir
TMP_DIR="/git/tmp/$BRANCH"
mkdir -p $TMP_DIR

# checkout repo to temp directory
git --work-tree=$TMP_DIR --git-dir="/git/cpd.git" checkout -f $BRANCH

# set remote server ip
if [ "$DEV_BRANCH" == "$BRANCH" ]; then
  REMOTE_IP="$DEV_IP
elif [ "$STG_BRANCH" == "$BRANCH" ]; then
  # REMOTE_IP="$STG_IP
elif [ "$UAT_BRANCH" == "$BRANCH" ]; then
  # REMOTE_IP=$UAT_IP
elif [ "PRODUCTION_BRANCH" == "$BRANCH" ]; then
  # REMOTE_IP=$PRODUCTION_IP
fi

# set the remote folder
REMOTE_FOLDER="git@$REMOTE_IP:/datadisk/sites"

# make sure we have an ip then sync the individual domains
if [ -z "REMOTE_IP" ]; then

    rsync -vzre ssh --delete "$TMP_DIR/" $REMOTE_FOLDER/bics
    rsync -vzre ssh --delete "$TMP_DIR/" $REMOTE_FOLDER/cha
    rsync -vzre ssh --delete "$TMP_DIR/" $REMOTE_FOLDER/iopf
    rsync -vzre ssh --delete "$TMP_DIR/" $REMOTE_FOLDER/ltp
    rsync -vzre ssh --delete "$TMP_DIR/" $REMOTE_FOLDER/poultrypassport
    rsync -vzre ssh --delete "$TMP_DIR/" $REMOTE_FOLDER/ptr

    echo "lantra cpd deploy > "$BRANCH"
fi

# remove temp files
rm -rf "$TMP_DIR"

