fieldLayouts:
  46202269-1d4b-4803-aef3-1a626eaf5054:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: fd1ee6f5-ed4b-471b-98bd-7c6951cce9c8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fbd50700-a63f-4a13-b729-1947510b8a14 # Attempt Unit
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0dee4c3e-2ad1-4a90-807f-78384168f5e1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4b25bd1b-f51c-4175-8db7-e871de866f2f # Attempt Answers
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9b9d7ef5-32a5-4501-b45f-eda23be096ea
            userCondition: null
            warning: null
            width: 100
        name: Attempt
        uid: 3c19df9e-ac04-4bdd-9a82-385a055b862a
        userCondition: null
handle: attempt
hasTitleField: false
name: Attempt
section: 51a18e4b-1a36-4210-8769-a5b8f28f3a5f # Attempts
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '[unit {attemptUnit.one.id}] {author.firstName} {author.lastName}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
