fieldLayouts:
  d12a8c7b-ca2c-4e5a-a2ea-56c7d843b0d7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 46a703cf-1585-4f87-8d91-cf615ffe7b6a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fa734878-4241-4654-86c9-50964d8a8692 # Company Primary Managers
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 84a86d3b-14a1-4bb6-81c8-a3b7731d5aea
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 8a8d1ecb-3c6c-4ade-a2e7-8e6996e7fe86 # Company Secondary Managers
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 87501ac3-1a49-4d2f-9276-3eb669c1de0a
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: a8d84419-f7b9-4d64-b7cb-ce827c7ca810 # Company Remaining Licences
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 65c53f64-a68d-4131-afa1-bd58a962ad5b
            userCondition: null
            warning: null
            width: 100
        name: Company
        uid: 2ffa17dc-69a4-42ae-ab07-861adc502611
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 75ec7211-a9c5-4390-963a-9d63dfd0dbd4 # Company Parent
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2ddcf175-3e91-4c51-b4da-58203861721e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3629d8e1-89dd-47fd-939f-c81889682a13 # Company Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 50f1fb1c-d92c-41a7-9424-41a18404dab5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 069f2a42-da65-478a-852e-18a44408ab93 # Data Clean Company Parent
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 453d9d18-57eb-4b18-832f-c9e19ce77285
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8e2495cf-1284-407e-b4eb-7bf9b4885d5b # Company Taskbooks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b6da3640-56a5-4a35-8831-9de6db7816dc
            userCondition: null
            warning: null
            width: 100
        name: Hierarchy
        uid: 772e766b-99a4-4c7c-8871-45890b3f7dd4
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: dc88c84b-17f2-4b8b-8cc6-124b5115c9cc # Legacy ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 580727c6-1ddf-490f-afc4-ab5b4c9103bf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3d52518d-7b85-4ef8-af1c-fb8a813e0cce # Legacy Parent ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 00ddd64c-4dfc-47bd-a93c-4d2f00e10de7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 440ee4d2-9c90-47a0-a2e7-9ec4d1a97683 # Data Imported
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6e1ec315-28b7-4f36-9d67-82f8acac5c2f
            userCondition: null
            warning: null
            width: 100
        name: Legacy
        uid: 3e16d288-bcc7-4a0d-90cd-4e2891c38b57
        userCondition: null
handle: company
hasTitleField: true
name: Company
section: 86faf121-d218-4348-8ab8-de457b46aa63 # Companies
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
