fieldLayouts:
  e0343ee1-0f38-4a11-b963-83087a5fb1e1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d3dab85d-768f-4a98-b35c-3da7d170bcf8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b44b14bb-77d3-4e81-9d72-9a478aa97053 # Result Company
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: db35d47b-9486-4df7-832a-176328eda14a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 295e5043-483c-4ad9-bfaa-bac22b99dc19 # Result Module
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4da819b0-7f03-442b-9157-515bfaa916c0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3ccae116-4500-45d0-a56a-024f2e8d4d03 # Result Status
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: adc4d88a-f52d-4bca-906c-99e063ee6e34
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fad66cc6-a49e-4a7d-955e-448c48ed449e # Result Linked Results
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a2e74eac-7522-4fb2-b8c6-a9886d53af5f
            userCondition: null
            warning: null
            width: 100
        name: Result
        uid: 9ff8e2d6-e4fe-4e16-98e5-1786adffc6b3
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 61e98c20-6536-4fb2-8420-7b21d34b4dd5 # Result Comments
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4319595a-9d0d-45db-be62-34b4642230be
            userCondition: null
            warning: null
            width: 100
        name: Comments
        uid: 67556290-61d5-4c31-aa8c-6d8b6bd8521c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 73b12e48-7a9e-496f-b91e-01fad8e389d1 # Cycle Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 44661c09-c158-4a41-b5a9-899eb2759662
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d3594414-790c-479e-ada1-8e93cd99e906 # Cycle Start Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: deeac4ad-91d5-4c19-8387-5413403d36e7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: af241f00-e550-43b0-9800-e6ce4d85919e # Cycle Finish Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 70046ffd-7fa3-4301-b622-916415401054
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 06f9a436-94f4-4170-80ec-6e08d13115ee # Result Hours
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8036e5da-0716-4068-affb-b9ef35f7d269
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b9aee86b-4af4-40aa-9673-848931e1e750 # Result Unendorsed Hours
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e6cfdcd4-e6fd-499b-9bbd-f7c6081c16c3
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: a1d83c2a-d7f2-45d2-8430-7e2efd8d12ec # Result Points
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1088d1df-bfbe-47ee-a6f9-7375bc8cd423
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 53db6462-0ded-4ff9-babe-8ed1294eec1b # Result Unendorsed Points
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: edd7400a-7fd4-4fa3-a246-b688e641cae2
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 77c7c383-632e-462f-984c-7ab34eb2cd1e # Result Component Results
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4ec5f63a-cb3f-46c4-8767-397fd7bae5d3
            userCondition: null
            warning: null
            width: 100
        name: 'CPD Cycle'
        uid: 48464199-04a6-4acd-9d33-9626e3e9a3d4
        userCondition: null
handle: moduleResult
hasTitleField: false
name: 'Module Result'
section: c0345752-9e56-4de1-a2d2-da641c3708e0 # Results
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 2
titleFormat: '[module {resultModule.one.id}] {author.firstName} {author.lastName} '
titleTranslationKeyFormat: null
titleTranslationMethod: site
