fieldLayouts:
  c7fc9695-dd0b-42be-9d6a-4b9b5476f8a8:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 006c28e4-4119-476d-bf1f-82019f947b02 # Package Level
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 164fe93f-d610-4819-8ca4-77cc4a88112e # Package Module Group
            instructions: ''
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 53fe1ed0-e4fe-4a51-8235-3f3a1b123528 # Package Taskbook
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 33d71c63-d5f5-42bb-a731-3a8df1f1759f # Package Revision
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5e4e967d-f646-4378-aedf-9f6ef84c1e28 # Package Job Role
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: edcdcb64-8b0b-4f31-ab57-106c9e252317 # Package Module Groups
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 534ba9ca-50bd-4b63-a843-b3358f1bc352 # Package Status
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Modules
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 60c37e60-aa57-4044-8164-0fbd42dc6127 # Package Log
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Log
        sortOrder: 2
      -
        elements:
          -
            fieldUid: df065216-2242-4a91-8b81-fa97ca27d449 # Package Assessment
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Assessment
        sortOrder: 3
      -
        elements:
          -
            fieldUid: 3455bcb3-f959-4b7a-a64d-b0138268b594 # Package Workflow
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7f722e30-ba1b-49e0-a5f4-e7070b600311 # Package Reviews
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e5a97ebb-756a-40bb-9b81-231b8ad564b2 # External Status
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 29fe57f7-c3de-4f09-ac06-d78bfd960ea5 # External Assessor
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Reviews
        sortOrder: 4
      -
        elements:
          -
            fieldUid: 1e03a0c1-334b-4517-9560-d95c13db8a99 # Package Cost
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a9271765-2484-428e-8c34-62e30184b582 # Package Paid
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7f1c4f49-327b-48eb-b631-5950532840c2 # User Payments
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Payments
        sortOrder: 5
handle: package
hasTitleField: true
name: Package
section: 0c63d248-a060-4ecd-b881-00607c9f4024 # Taskbook Packages
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
