fieldLayouts:
  c7fc9695-dd0b-42be-9d6a-4b9b5476f8a8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7d468b3b-98f2-477c-8186-3d37f841559a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 53fe1ed0-e4fe-4a51-8235-3f3a1b123528 # Package Taskbook
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 381d7007-04e4-4a8f-9b11-93c48551a3a5
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 006c28e4-4119-476d-bf1f-82019f947b02 # Package Level
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4338a065-efd0-47fd-a57f-a2b9209ef159
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 33d71c63-d5f5-42bb-a731-3a8df1f1759f # Package Revision
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7611a4f3-aa33-485b-8df6-6dc1aa94f59d
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 5e4e967d-f646-4378-aedf-9f6ef84c1e28 # Package Job Role
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8ef522eb-7242-4a21-9c16-580de307097b
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: edcdcb64-8b0b-4f31-ab57-106c9e252317 # Package Module Groups
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4888472-6cd4-4667-84a9-79aec4cb139c
            userCondition: null
            warning: null
            width: 100
        name: Modules
        uid: 7e29f947-5619-428f-b89e-fa5f50c909ef
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3455bcb3-f959-4b7a-a64d-b0138268b594 # Package Workflow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 93693c94-22f6-47b3-8d88-43e4b74a5937
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 534ba9ca-50bd-4b63-a843-b3358f1bc352 # Package Status
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c635f13a-8e3f-4e73-8916-8339506b1c0e
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 7f722e30-ba1b-49e0-a5f4-e7070b600311 # Package Reviews
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e560d55-a5d2-48b6-8865-f57d8b7e3d26
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e5a97ebb-756a-40bb-9b81-231b8ad564b2 # External Status
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1b7cabbe-c938-4dc2-842a-9c6d4ca7998f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 29fe57f7-c3de-4f09-ac06-d78bfd960ea5 # External Assessor
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0b39d2cd-ba8f-4355-9b72-11d09e73aa3c
            userCondition: null
            warning: null
            width: 50
        name: Reviews
        uid: 8a499a29-403f-48a6-a71f-c945fab60ed0
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: df065216-2242-4a91-8b81-fa97ca27d449 # Package Assessment
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e2eea4c3-7565-491f-a0ce-b07cf1d7bc26
            userCondition: null
            warning: null
            width: 100
        name: Assessment
        uid: 416cc00a-0bd8-4c69-be0a-7c4b7f885321
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 1e03a0c1-334b-4517-9560-d95c13db8a99 # Package Cost
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dc575a5f-df28-4caf-ab88-c6ccc4c5c69d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: a9271765-2484-428e-8c34-62e30184b582 # Package Paid
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6f616e69-28bd-48a5-985f-5883fe3105fc
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 7f1c4f49-327b-48eb-b631-5950532840c2 # User Payments
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c1157736-d979-4317-a6f1-a974934a882e
            userCondition: null
            warning: null
            width: 100
        name: Payments
        uid: cbb56b48-af9f-410a-8aa3-dcf3b0b14c91
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 60c37e60-aa57-4044-8164-0fbd42dc6127 # Package Log
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e9bc655d-68d9-4199-b75e-ea102697eb9e
            userCondition: null
            warning: null
            width: 100
        name: Log
        uid: 3a7e8288-d6de-44a4-a528-12f29b8ad820
        userCondition: null
handle: package
hasTitleField: true
name: Package
section: 0c63d248-a060-4ecd-b881-00607c9f4024 # Taskbook Packages
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
