fieldLayouts:
  6d710b1b-95a9-4417-b0dd-78a03a5baa40:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b5d5a176-b3ad-459e-ba9c-b5575a778bab
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6b431a5f-e1ee-4520-ab30-89ca72993c00 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 23f18c18-0077-4099-ae50-714411ca2daa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b8c430cf-c3d3-4d15-a8a8-21eb2fb94ace # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a1e9e875-918e-4121-aebf-15f87074ab07
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5d8461b5-aba0-482c-a677-b59c1ec759ab # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f1205aa0-3fdd-41e7-8d84-d6c34726aa02
            userCondition: null
            warning: null
            width: 100
        name: Pages
        uid: fd5be65a-3560-4891-a01c-b450cd109d57
        userCondition: null
handle: pages
hasTitleField: true
name: Pages
section: 8c1af673-0f01-4434-a6f0-86f01675d799 # Pages
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
