fieldLayouts:
  f54eef12-6131-4721-94a4-834583923074:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 75
          -
            fieldUid: db267693-1bd5-427d-b65d-4f74c7f0f42d # Product Company
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 26b4e668-8bdc-4798-bc5f-7cd76851378f # Product Manufacturer Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 941f2df5-26eb-4a6c-8772-f52e0fd5789b # Product Manufacturer Email
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Product
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 53b87ea0-021a-4671-bfbd-8000933bcf0e # Custom Fields
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Custom Fields'
        sortOrder: 2
handle: product
hasTitleField: true
name: Product
section: 3d20ce59-1bf4-4cb2-a4b9-1c04d290e5ad # Products
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
