fieldLayouts:
  54d3df5e-cef1-4cdf-9279-a811f0717781:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2eccfd54-2157-466c-9b5b-ad36419b5b30
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f7a6d059-9c07-4f32-a734-4bd9b5f2e210 # Result Start Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 98b06851-0fd1-4631-b586-7c320754aaf9
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 5178135a-3ba7-41aa-9440-4766d3c07a31 # Result Product
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a834323e-da01-4cd1-a2cb-e3977651ab2f
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: e7ff470a-3e85-47be-9037-1508ea540121 # Result Evidence
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5ba9b2c6-4190-47f7-b39e-2cfa28cb4060
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7099187a-6e5d-4af0-8440-0063a8bc7585
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a75d2fa6-54eb-4155-9483-d7729fb83004 # Result Custom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6d220f98-08bd-4fae-9249-adeb60ca7a7a
            userCondition: null
            warning: null
            width: 100
        name: 'Custom Values'
        uid: 40073809-38ef-473c-a2c7-fc00eb7f9105
        userCondition: null
handle: productResult
hasTitleField: true
name: 'Product Result'
section: c0345752-9e56-4de1-a2d2-da641c3708e0 # Results
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 4
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
