fieldLayouts:
  54d3df5e-cef1-4cdf-9279-a811f0717781:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9b8f263c-805b-4b3e-8650-76e1a6b867a3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f7a6d059-9c07-4f32-a734-4bd9b5f2e210 # Result Start Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 85f32d99-ba7d-4181-bfbf-40a76a118595
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 5178135a-3ba7-41aa-9440-4766d3c07a31 # Result Product
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 365e7ae7-b6c3-4fe8-9196-f0d899dc41de
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: e7ff470a-3e85-47be-9037-1508ea540121 # Result Evidence
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dd69a4eb-565e-4b17-8017-c9bd04dffdae
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 30d9e6f7-1bcf-4acf-9df1-9fbae0d5fd3f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a75d2fa6-54eb-4155-9483-d7729fb83004 # Result Custom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bd536438-66c4-42ed-94cd-876f65a60c31
            userCondition: null
            warning: null
            width: 100
        name: 'Custom Values'
        uid: d1f55def-3aa9-4522-8aa3-fcf99ac8392f
        userCondition: null
handle: productResult
hasTitleField: true
name: 'Product Result'
section: c0345752-9e56-4de1-a2d2-da641c3708e0 # Results
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 4
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
