fieldLayouts:
  70e84763-f654-4aea-8ba8-7ef0b4a62538:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 916a331a-73b0-4102-9cea-9ffee3b08977
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fbd8c758-3ca5-4ccb-8452-d1d82d3f97e4 # Module Group
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dd891a6d-c65a-4046-b74b-a92630f605d0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6b431a5f-e1ee-4520-ab30-89ca72993c00 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ff375042-c0f7-4a37-ab57-4e557d250a42
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d99d90fa-6251-4b71-9340-542bc9c3feb9 # Module Notes
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7c07053f-a0f6-456e-99fa-2098358e6627
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 646454e2-66f9-4f03-bac7-b94a89aba17a # Module Expiry Days
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e544ba32-e818-4708-8ba9-3b361e60de8c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3bfea235-c57e-4998-b079-8c15a1ebbf0e # Hide Add Achievement?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f98e2a20-a6b0-4e12-ad23-8b5eba64d57d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6b856e7c-77f4-4646-9dc9-81cd812d3919 # Achievement Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca5b751d-0e5d-40cb-8a3f-9db0f24549a1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6f94bf9b-3168-437e-b8f2-7d082dcdd831 # Unit Groups
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ba6805f5-2c75-42f3-a9b3-5a6771bca858
            userCondition: null
            warning: null
            width: 100
        name: Module
        uid: ec673a8d-03fe-483e-a3a7-e316d0b71bfc
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f08f684f-1af1-417b-94f2-5df2f3ac7da6 # Job Roles
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 82b56c76-b2ad-41c5-82db-eb03e71ab4b3
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 3e71d4f7-d155-457a-9e53-497f9c3ff348 # Module Optional
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4515ab92-8ef6-4995-95ae-3acb19f7e6a7
            userCondition: null
            warning: null
            width: 50
        name: 'Job Roles'
        uid: 59b001e6-815a-4bad-8a4e-4f3f6a88ff41
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: bfce8aaa-028f-4d73-8f1d-20ba8f5a871b # Column Layout
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5488f61f-6b8d-4dcf-9ff1-4da76165f29e
            userCondition: null
            warning: null
            width: 100
        name: 'Column Layout'
        uid: 5f00b0a7-17b9-47b2-8b45-da1a33c0aa6b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 44d48073-7cb3-44e1-a245-66bbb18eefa7 # Is Skills Matrix?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e36d4f65-2417-4df1-b989-6d788b8a95c4
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: d34de3f0-4642-49dd-a796-fa9098339e54 # Skill Levels
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7d24148e-5233-426b-a9ba-e839ad1c9b79
            userCondition: null
            warning: null
            width: 75
        name: 'Skills Matrix'
        uid: 7457dcf2-1c91-4f43-bcdf-12d5e4688aa1
        userCondition: null
handle: qualification
hasTitleField: true
name: Qualification
section: e9e30b72-2c16-4035-b4b9-e1e4c42ebb3a # Modules
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
