fieldLayouts:
  70e84763-f654-4aea-8ba8-7ef0b4a62538:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: fbd8c758-3ca5-4ccb-8452-d1d82d3f97e4
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 6b431a5f-e1ee-4520-ab30-89ca72993c00
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: d99d90fa-6251-4b71-9340-542bc9c3feb9
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 646454e2-66f9-4f03-bac7-b94a89aba17a
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 3bfea235-c57e-4998-b079-8c15a1ebbf0e
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 6b856e7c-77f4-4646-9dc9-81cd812d3919
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 6f94bf9b-3168-437e-b8f2-7d082dcdd831
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Module
        sortOrder: 1
      -
        elements:
          -
            fieldUid: f08f684f-1af1-417b-94f2-5df2f3ac7da6
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Job Roles'
        sortOrder: 2
      -
        elements:
          -
            fieldUid: bfce8aaa-028f-4d73-8f1d-20ba8f5a871b
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Column Layout'
        sortOrder: 3
handle: qualification
hasTitleField: true
name: Qualification
section: e9e30b72-2c16-4035-b4b9-e1e4c42ebb3a # Modules
sortOrder: 1
titleFormat: ''
