fieldLayouts:
  70848f31-dc12-428f-873c-12acd93bbd10:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: d1300c08-840a-419d-b910-de865842ddd8 # Report Description
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1a27fa24-b0d3-491d-8b77-f1656c3afc77 # Report Type
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bebe1bc3-81ca-46c1-86ac-1ad88d0a0f92 # Report Count
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1a8a5dc7-66a0-4520-957d-7dec3aa3cf2f # Report Last Sent Date
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f6e76a64-5565-406e-8679-27b8adea6736 # Report Automated
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Reports
        sortOrder: 1
      -
        elements:
          -
            fieldUid: dd61054f-d009-4e76-9315-7bf23e0cbc22 # Report Result Type
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d4776dfe-b66f-4a88-931c-d2bebb2d68d1 # Report Companies
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d500f1e4-fb5b-435a-af01-cc2402b4a8c3 # Report All Companies
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ab55340f-38e6-4d9f-82eb-f3785c6c6ff8 # Report Include Hierarchy
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: abb92e86-cb1b-456e-a618-befafa8e8a28 # Report Teams
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7b7af1dc-c01f-4f73-b3f4-a83ff572e941 # Report All Teams
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2f940be6-d44c-47bf-95b6-392608ee2547 # Report Roles
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 27e57a2d-2938-41e8-ab58-72f377ca20c1 # Report All Roles
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a1b63d62-c6f0-443b-910f-1d6691b0e4a4 # Report Units
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e05af851-b6aa-4f59-a43b-0ac897b54887 # Report All Units
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c2e23d12-1d3f-4cbd-a3cb-be22ea64bdca # Report Modules
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c9d661c9-fd44-473b-a7ef-70f4bc6340ea # Report All Modules
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8200bbc7-18f0-49da-a017-2fb3a82ee950 # Report Result Expiry
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f56275dc-26a8-46e7-bfb5-061917775684 # Report Display Field
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 19bb4e6d-2834-456c-93b9-6b942b47b8d4 # Report Include Expired
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d4ac5d73-4f3c-467c-a3c4-492a2205f858 # Report Include Required
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Criteria
        sortOrder: 2
      -
        elements:
          -
            fieldUid: e0c4c343-2eda-4447-baf6-836f09723985 # Report Recipients
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 84ec75d0-1dcf-408a-bce8-4ea7b5370c3b # Report Emails
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: dbedebea-c884-4f61-8f0f-ebc64b3a5ed2 # Report Send Frequency
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c996fdb5-0318-4df3-87bd-b42b45db2cab # Report Send Value
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Recipients
        sortOrder: 3
      -
        elements:
          -
            fieldUid: c0866ad5-ca17-43d8-8a57-52ea3e84bbe2 # Report Data
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Data
        sortOrder: 4
handle: reports
hasTitleField: true
name: Reports
section: 1d590683-b16e-4955-be62-315accb3e628 # Reports
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
