fieldLayouts:
  e8d523cd-161e-4cf6-9d36-39e2d444cc43:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4818cb27-b845-40d9-8271-e136bb9b5ef5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 892d5048-f63d-468f-a926-c89daebf07f9 # Short Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0e1055b8-3d87-4eae-9128-a9335c1132e5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 918cc95b-e5c3-468d-809a-8bbd4eb5a8e5 # Taskbook Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 16fe78b3-c7b3-4f6a-ae1a-514977fd6fef
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: db4d8830-6fbb-45c9-bdb4-cc058820b1ae # Taskbook Files
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 769974d1-7923-4307-9b88-9693feeafd26
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3455bcb3-f959-4b7a-a64d-b0138268b594 # Package Workflow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7e66d7ed-9850-4c19-ae0d-cc50ca6099ac
            userCondition: null
            warning: null
            width: 100
        name: Intro
        uid: f31fc426-9d42-4ca0-a95a-2d78bf838ae8
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 497fe30b-60db-4d82-a39f-a64da4fc64f4 # Taskbook Module Groups
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1da3327e-975a-48fd-b1e1-14389f8bc9da
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 15bbefca-0655-4916-b7c1-1cc34ce71903 # Taskbook Fixed Levels
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b970db9a-4f6b-407e-be6d-c27cfce2be05
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 84396576-ea02-4748-adcd-ae3fe8d26824 # Unit Endorse
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f7745b8f-c8a7-472a-b092-db9c0d859d22
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: aad3447b-fda9-4047-8248-83ebf802ecb8
            userCondition: null
          -
            elementCondition: null
            fieldUid: da81a368-f84c-47f8-9e3a-b83346be0865 # Module Group Minimum Optional
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6a8f1521-5292-43ab-8ec4-15346994e8a9
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: e1c8bc22-c8ae-487a-8cfa-074338772cbc # Module Group Minimum Credits
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d01a6e71-a53b-487d-a7f3-a1af42969f37
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 753f71f4-d39b-43bd-9219-b76f91626502 # Module Group Minimum Level
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 82af3307-5030-46ef-8cdc-1749b4eb48f6
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 809b8647-dd59-44cf-b5d5-63dac0021cb1 # Module Group Minimum Level Credits
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 69940f63-d779-4889-98f6-c0055fda281c
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 74fbb85d-d2cb-4378-9d06-c3c471184915
            userCondition: null
          -
            elementCondition: null
            fieldUid: 699e2d79-cad0-47dc-b93d-e55e9c9ddf50 # Unit Result Rollover
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 09ee6b3b-a1c9-4aaf-9c25-35315478423b
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 5e4a7ca4-f994-4dcc-a450-46e5a57f32fa
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ab5af452-7d2f-4498-9a76-6ffbe1c7a251 # Taskbook Free
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ce7ea192-3133-42df-96c8-86f9a5e78150
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: e427fbb1-c8bc-4ad3-9913-e5c7931d63f2 # Module Group Max Cost
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 953b71bf-670c-4ac5-b18f-15817a8f13e2
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 5bdda926-785f-4d89-aebe-9a805b3dab29 # Module Group Resit Cost
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 05f7653d-8db8-4233-88a2-9c3cee04e096
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 294cd8d8-83ae-4d68-a8b1-5acd3d3f6ca3 # Module Group Single Cost
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 08e750d8-3451-4c87-826b-d61728de0803
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 680431de-8445-48e9-8acf-e32d867f73dd # Module Group Costs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b99ccef6-e919-444c-af91-cda8e6f447a7
            userCondition: null
            warning: null
            width: 100
        name: Costs
        uid: 961e5692-60f3-45ba-8654-d62f29176736
        userCondition: null
handle: taskbook
hasTitleField: true
name: Taskbook
section: 0db8b604-3d85-4638-bc64-f1d73e2e9aba # Taskbooks
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
