fieldLayouts:
  cc195c64-b902-4637-9825-d5fc0d27b48e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a65a3fb1-448e-4e77-9227-cb898083d56a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 892d5048-f63d-468f-a926-c89daebf07f9 # Short Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4dbc9964-381e-425e-bd7f-e5640ef69a3b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 57f129b9-c872-49ad-9f42-c2b3c1f84753 # Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bcdaae2d-91e6-4229-8e7e-da71f7ad57c5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fbd8c758-3ca5-4ccb-8452-d1d82d3f97e4 # Module Group
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 86545edc-a7a2-497f-bc6d-ff10395864d6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6b431a5f-e1ee-4520-ab30-89ca72993c00 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 38329cfe-77ca-4775-ba52-f5e3d4f0ad31
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6f94bf9b-3168-437e-b8f2-7d082dcdd831 # Unit Groups
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a8d7749a-9581-4da5-a758-cf1d6285cd70
            userCondition: null
            warning: null
            width: 100
        name: Module
        uid: 760e826c-958e-4316-9935-94e5f060ad56
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: bfce8aaa-028f-4d73-8f1d-20ba8f5a871b # Column Layout
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f14ea30-4a7a-4e22-8096-90f7237734f0
            userCondition: null
            warning: null
            width: 100
        name: 'Column Layout'
        uid: 761b4491-70b5-4327-b545-fd41d04da40d
        userCondition: null
handle: taskbook
hasTitleField: true
name: Taskbook
section: e9e30b72-2c16-4035-b4b9-e1e4c42ebb3a # Modules
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 3
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
