fieldLayouts:
  e8d523cd-161e-4cf6-9d36-39e2d444cc43:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 5df92654-19a4-446e-a578-2b359d4bc88f
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 840f8f48-be42-4008-ae9e-1fa132183769
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: f4f743d8-8e66-4bb5-920a-01bd366d6ba2
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Pages
        sortOrder: 1
handle: taskbooks
hasTitleField: false
name: Taskbooks
section: 0db8b604-3d85-4638-bc64-f1d73e2e9aba # Taskbooks
sortOrder: 1
titleFormat: '{section.name|raw}'
