fieldLayouts:
  bcaf5920-c460-4465-a5db-e7f4bad29958:
    tabs:
      -
        elements:
          -
            instructions: null
            label: null
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: fcef71c8-c93e-4e97-a8f3-4fc223b2d223
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 0578b9f0-6e63-4ecd-b386-295f3b276282
            required: true
            type: craft\fieldlayoutelements\CustomField
        name: Team
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 5839b521-ccd0-4768-bbe4-ef59335fb732
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 838b996f-8f5d-4df2-9a75-0d1692348632
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Managers
        sortOrder: 2
handle: team
hasTitleField: false
name: Team
section: bcf0ea1d-9495-423e-ac83-ef089790460c # Teams
sortOrder: 1
titleFormat: '{teamCompany.one.title} - {teamName}'
