fieldLayouts:
  0070d453-42a5-4800-b0a7-8bbdb55954c6:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 14b8c677-a8a8-4df3-a74e-a30106bd5398 # Result Owner
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: b44b14bb-77d3-4e81-9d72-9a478aa97053 # Result Company
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 3103beed-feb4-4eed-b71a-68cb81d67f7e # Result Unit
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 3ccae116-4500-45d0-a56a-024f2e8d4d03 # Result Status
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 5828e048-752b-48b2-922d-f3743be7d970 # Result Outcome
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 5dd21124-5f28-49d6-8f3e-d70184415478 # Result Endorsed Date
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 3cff7796-6519-48a5-97e7-e4dbb14befcc # Result Endorsed User
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: d09c7ee9-90ad-4c7e-a8ec-a84e5f3457f0 # Unit Endorsement Manager Level
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 2c8efd67-eb2c-40fd-b9d3-f660cc251a99 # Result Module Result
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 20ebe212-6fe5-4cd3-8045-a82a1c462e88 # Result Recurring Cycle Code
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: fabb8307-8d88-4171-bfe1-3309efb0b71a # Result Date Required
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 119c90c9-10db-4cf5-aa99-01416a994a39 # Skill Level
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: a45ed781-89d0-4ad7-a368-7367569ce265 # Result Upskiller
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: 2123df89-a793-417a-bba8-a28f4cddca4d # Is Taskbook?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 4556c45d-9692-44ba-aed8-56d8ce7f36a7 # Result Package
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: aecf7067-ebfd-4bd0-8360-cd167eac91d3 # Result Module Group
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
        name: Result
        sortOrder: 1
      -
        elements:
          -
            fieldUid: e7ff470a-3e85-47be-9037-1508ea540121 # Result Evidence
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f7a6d059-9c07-4f32-a734-4bd9b5f2e210 # Result Start Date
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c29bb59d-f545-409b-be92-c9b57e8cf603 # Result Finish Date
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d363cf24-3e53-4eea-b5f4-e9c72a3e9f65 # Result Location
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 06f9a436-94f4-4170-80ec-6e08d13115ee # Result Hours
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 82f069e1-b11c-4e0d-96f6-eaf3e5d58387 # Result Narrative
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 53ded07f-6c81-4e7c-8e25-520b62d1a532 # Result Notes
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a1d83c2a-d7f2-45d2-8430-7e2efd8d12ec # Result Points
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Evidence
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 6cb9aa27-e25b-4a44-8dca-f20fca5f3588 # Result Attempts
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5af516f7-8267-4333-b0d0-0ff4f5ee41bb # Result Score
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Test
        sortOrder: 3
      -
        elements:
          -
            fieldUid: 61e98c20-6536-4fb2-8420-7b21d34b4dd5 # Result Comments
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Comments
        sortOrder: 4
      -
        elements:
          -
            fieldUid: a75d2fa6-54eb-4155-9483-d7729fb83004 # Result Custom
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Custom Values'
        sortOrder: 5
      -
        elements:
          -
            fieldUid: 0b692c2e-5b0e-43b1-911a-f5052b808cf5 # Legacy Result Files
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 440ee4d2-9c90-47a0-a2e7-9ec4d1a97683 # Data Imported
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Legacy
        sortOrder: 6
handle: unitResult
hasTitleField: false
name: 'Unit Result'
section: c0345752-9e56-4de1-a2d2-da641c3708e0 # Results
sortOrder: 1
titleFormat: '[unit {resultUnit.one.id}] {author.firstName} {author.lastName}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
