fieldLayouts:
  0070d453-42a5-4800-b0a7-8bbdb55954c6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 47cda1ac-7f21-4583-ab9e-3726d2e35237
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 14b8c677-a8a8-4df3-a74e-a30106bd5398 # Result Owner
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a95f8cc-ab18-4e52-937c-5aaef6e6bfa5
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b44b14bb-77d3-4e81-9d72-9a478aa97053 # Result Company
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8fc33875-5806-4b0c-9e48-3c57b0a20f30
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 3103beed-feb4-4eed-b71a-68cb81d67f7e # Result Unit
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ad0699aa-466e-413c-9bf3-1bd3fe5a14a2
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 3ccae116-4500-45d0-a56a-024f2e8d4d03 # Result Status
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c052708c-1528-4675-893e-63cb853acf17
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 5828e048-752b-48b2-922d-f3743be7d970 # Result Outcome
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8354624d-73ea-41bc-b35f-cd6a7af94b04
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 5dd21124-5f28-49d6-8f3e-d70184415478 # Result Endorsed Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aa7e71de-9f44-40fe-b96f-e589703e2c5a
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 3cff7796-6519-48a5-97e7-e4dbb14befcc # Result Endorsed User
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 239e802b-081c-44bd-82c6-5df0df0b9865
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: d09c7ee9-90ad-4c7e-a8ec-a84e5f3457f0 # Unit Endorsement Manager Level
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c144391a-9ff0-4745-9e1c-7454cf78cfd7
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 2c8efd67-eb2c-40fd-b9d3-f660cc251a99 # Result Module Result
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf381e3b-e8d0-4385-a07c-18bcb7c0d86b
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 20ebe212-6fe5-4cd3-8045-a82a1c462e88 # Result Recurring Cycle Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 602191b8-d809-49f8-8b9c-ef52fe5aed76
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: fabb8307-8d88-4171-bfe1-3309efb0b71a # Result Date Required
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6d15dd9a-017e-494c-a190-eec013212529
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 119c90c9-10db-4cf5-aa99-01416a994a39 # Skill Level
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e97c948d-127d-40a8-b332-11ab33ccdb5e
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: a45ed781-89d0-4ad7-a368-7367569ce265 # Result Upskiller
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 86f15b5e-7da2-4cb1-b283-842a7c591de8
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 837dea33-e829-43ec-a570-f700d55e5107
            userCondition: null
          -
            elementCondition: null
            fieldUid: 2123df89-a793-417a-bba8-a28f4cddca4d # Is Taskbook?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bf8e4a02-5f76-4ed0-8117-fc17b0184736
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 4556c45d-9692-44ba-aed8-56d8ce7f36a7 # Result Package
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 489ceb9f-b744-4fbe-b103-d8d29b3c0f14
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: aecf7067-ebfd-4bd0-8360-cd167eac91d3 # Result Module Group
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 39a92aa1-5ace-4f93-bf25-6094ca72c1c4
            userCondition: null
            warning: null
            width: 25
        name: Result
        uid: d39cb767-a034-433b-8490-b511a637673c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e7ff470a-3e85-47be-9037-1508ea540121 # Result Evidence
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 69c611f0-a528-4b89-8161-70df4cbe7b5c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f7a6d059-9c07-4f32-a734-4bd9b5f2e210 # Result Start Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a30300ab-3639-4efd-9878-fa4bc6676812
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c29bb59d-f545-409b-be92-c9b57e8cf603 # Result Finish Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b8c246fb-d34b-4e64-8948-dbf5cab02315
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d363cf24-3e53-4eea-b5f4-e9c72a3e9f65 # Result Location
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: efba27de-f13d-4231-9535-619743b0682a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 06f9a436-94f4-4170-80ec-6e08d13115ee # Result Hours
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e454bf4-9958-4455-bea9-968669f4a471
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 82f069e1-b11c-4e0d-96f6-eaf3e5d58387 # Result Narrative
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f303f6cb-66c0-49ab-8d7c-01b5830ec731
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 53ded07f-6c81-4e7c-8e25-520b62d1a532 # Result Notes
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a6fa5843-b7c4-46a7-8ae9-032fcb00047f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a1d83c2a-d7f2-45d2-8430-7e2efd8d12ec # Result Points
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f8f9a8cf-cafe-4c75-9238-6bab6f2df88c
            userCondition: null
            warning: null
            width: 100
        name: Evidence
        uid: f434e429-0a46-47a8-9e0d-3ee0f22ef1c1
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6cb9aa27-e25b-4a44-8dca-f20fca5f3588 # Result Attempts
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dce15f9b-266f-4aa2-87a8-a1b4677aad28
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5af516f7-8267-4333-b0d0-0ff4f5ee41bb # Result Score
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 08296082-aff8-4b70-b61f-e32da91f0e00
            userCondition: null
            warning: null
            width: 100
        name: Test
        uid: 0e79b9a6-34a2-49a8-bde7-75c8301619c2
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 61e98c20-6536-4fb2-8420-7b21d34b4dd5 # Result Comments
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b3e5cc14-889d-4a5e-9d73-fea8af678c42
            userCondition: null
            warning: null
            width: 100
        name: Comments
        uid: 364ac241-75b0-4668-a2a5-77c719fd46f7
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a75d2fa6-54eb-4155-9483-d7729fb83004 # Result Custom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f557d4ba-f571-499c-97aa-00e0ad270119
            userCondition: null
            warning: null
            width: 100
        name: 'Custom Values'
        uid: 0f70236c-013a-40c9-b5ff-60da9cc2d38d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0b692c2e-5b0e-43b1-911a-f5052b808cf5 # Legacy Result Files
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 02a2ede2-a013-402d-a24a-3f1a55f01e2b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 440ee4d2-9c90-47a0-a2e7-9ec4d1a97683 # Data Imported
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d7b441ec-d1bc-4d54-90ef-e16c4e969f5f
            userCondition: null
            warning: null
            width: 100
        name: Legacy
        uid: 72ad23c3-359c-40cc-8ac8-c88ba49f1fb5
        userCondition: null
handle: unitResult
hasTitleField: false
name: 'Unit Result'
section: c0345752-9e56-4de1-a2d2-da641c3708e0 # Results
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '[unit {resultUnit.one.id}] {author.firstName} {author.lastName}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
