fieldLayouts:
  3d94edeb-73ba-41ad-b224-c77a85c59742:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a0cd1c6c-afec-487b-8746-1a7f6f11efac
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f2ab3047-5922-481b-a6bc-d1ced215dc10 # Unit Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a68bdddb-b0b9-479d-a0a1-956f60a806ce
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 98e01bd1-bcac-4523-8399-0c55010d13b6 # Unit Tootlip
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e603790-6c21-4778-baee-4d19e9542706
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 995ba33c-928b-43a5-8d39-53c4c36782ed # Unit Type
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b44ddd5a-565e-436e-b204-526e0395c987
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c708fb49-2ead-4372-bb3f-c925d3ab9f41 # Unit Points
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d4f8b2a2-3eca-43d1-8b49-171809a6d930
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d09c7ee9-90ad-4c7e-a8ec-a84e5f3457f0 # Unit Endorsement Manager Level
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 45220e29-328e-437b-a97d-84e7ad88a9bd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6616a98b-5530-40e0-93db-6e73e439e274 # Unit Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 90a2e241-75e0-42e1-880b-8e46385ea67c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4bb00585-cc77-465a-add8-7acdffe931ce # Unit Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c9616b1e-a976-4564-9038-f46e37eb2a4f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1e5a2205-0d2d-4f4c-b087-a5f706ac0449 # Unit Files
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cc8febfb-10e7-433b-853a-de4e6244ce31
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 28e570b6-14a0-4b5e-be07-37e03f6b9b8f # URL (e-learning)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1392b314-dbb3-4c5c-949b-886c7ad77cac
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1d522b30-9aa0-4fc8-afd1-84e738233479 # Certificate
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 04ea24e0-2574-4587-b1b2-df35564cfe6b
            userCondition: null
            warning: null
            width: 100
        name: Unit
        uid: 1cc31dfd-43c6-4269-92f2-5ba5dcab4c47
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9b7c5c06-f32f-4771-b3bb-820327282329 # Test Complete Taskbook
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e335801a-162f-462d-b7c8-2483db0ca765
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8a7a272d-f35d-4ec6-9c9a-571c7f0f40d7 # Test Pass Percent
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3848c3ea-1162-4850-accd-28cab2011280
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4209884c-57c0-48b6-bb15-06361f5e0182 # Max Attempts
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f012880-4641-45e3-b5cc-059de20e6119
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e875ae7a-06f3-4063-a7c9-0b3fbb8f75b9 # Test Questions
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2699f6a9-85c3-4fde-9009-23dc2fae9ffc
            userCondition: null
            warning: null
            width: 100
        name: Test
        uid: 81b9195f-1fc0-4f52-9013-b14e9f353e62
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 556fe388-9b99-4cda-835a-bc491fa00273 # Unit Recurring
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b9fa27d7-674a-4776-809c-2a3366353179
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 22f6cba0-1e8a-4d82-8678-9a33b1d06163 # Unit Recurring Period
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cc9d0db7-a878-4e2e-ae91-1099ff87a185
            userCondition: null
            warning: null
            width: 100
        name: Reccuring
        uid: 2629be73-328e-49fc-a588-8e7301ceb5cf
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: dc88c84b-17f2-4b8b-8cc6-124b5115c9cc # Legacy ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1b41b686-583e-4687-ae77-957a2461b023
            userCondition: null
            warning: null
            width: 100
        name: Legacy
        uid: 75faee9d-267d-4a6f-9397-076b66b418d7
        userCondition: null
handle: unit
hasTitleField: true
name: Unit
section: 090b3c24-a9ac-4935-a919-c4fc8a3099b0 # Units
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
