fieldLayouts:
  457440da-2f23-4b47-8267-fcdfef51b254:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ba3185e5-25e1-4691-9e86-70d1c1593e64
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 14b8c677-a8a8-4df3-a74e-a30106bd5398 # Result Owner
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 320a1da6-bef4-4d57-85a3-d63637bfab10
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3ccae116-4500-45d0-a56a-024f2e8d4d03 # Result Status
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d35248be-8e26-485c-b1d9-f5536f0da3cb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5dd21124-5f28-49d6-8f3e-d70184415478 # Result Endorsed Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 465b2b23-c770-482a-8373-1fd797790c18
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3cff7796-6519-48a5-97e7-e4dbb14befcc # Result Endorsed User
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 96e09955-c461-414d-b43c-8b38dbd5c89b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2c8efd67-eb2c-40fd-b9d3-f660cc251a99 # Result Module Result
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 00042544-a023-40ae-b2b0-06eed4f9389a
            userCondition: null
            warning: null
            width: 100
        name: Result
        uid: f1c35bdd-294b-497a-8297-0d17f9dc4945
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e7ff470a-3e85-47be-9037-1508ea540121 # Result Evidence
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6b5d5051-9a10-4659-b8a7-3a2c23ecfcc9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f7a6d059-9c07-4f32-a734-4bd9b5f2e210 # Result Start Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 699f6321-4d43-4f83-923d-b804a090f64c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c29bb59d-f545-409b-be92-c9b57e8cf603 # Result Finish Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a7706617-5f71-4295-b144-75ccb0e53b65
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d363cf24-3e53-4eea-b5f4-e9c72a3e9f65 # Result Location
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c5fd871-e4bb-41a1-8b0e-a150b7ea1c97
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 06f9a436-94f4-4170-80ec-6e08d13115ee # Result Hours
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 559a1c68-ea0d-4411-a654-35eea8d6c117
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 53ded07f-6c81-4e7c-8e25-520b62d1a532 # Result Notes
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 182f06b4-42ab-4838-9b38-ee774bf8c678
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 82f069e1-b11c-4e0d-96f6-eaf3e5d58387 # Result Narrative
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d031efb6-a42b-4f15-8857-013423ad3507
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d09c7ee9-90ad-4c7e-a8ec-a84e5f3457f0 # Unit Endorsement Manager Level
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 329befe6-5233-47ab-9b26-e4bf342e68ef
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 295e5043-483c-4ad9-bfaa-bac22b99dc19 # Result Module
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 29fe79f8-1781-43ad-951b-a42e03093b88
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3103beed-feb4-4eed-b71a-68cb81d67f7e # Result Unit
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4102d500-60f0-4ff8-aeb1-96b03dbac8c2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a1d83c2a-d7f2-45d2-8430-7e2efd8d12ec # Result Points
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c4bb7da5-212a-4678-8193-ed0af53839d3
            userCondition: null
            warning: null
            width: 100
        name: Evidence
        uid: cd84f03f-50bd-4b17-9299-ab2b51e47d3c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 61e98c20-6536-4fb2-8420-7b21d34b4dd5 # Result Comments
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: badd8f27-b125-45a5-9a11-da2b5caa5c1b
            userCondition: null
            warning: null
            width: 100
        name: Comments
        uid: 1ce381d7-1ed0-461b-8e00-8e6f55192f58
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a75d2fa6-54eb-4155-9483-d7729fb83004 # Result Custom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 82af4c9e-7089-4f16-88dd-c1e66393bf27
            userCondition: null
            warning: null
            width: 100
        name: 'Custom Values'
        uid: 5143edd5-7194-40da-ac0f-66506f1f25fa
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0b692c2e-5b0e-43b1-911a-f5052b808cf5 # Legacy Result Files
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 015022bd-4340-482c-b251-c7b5ab02d8ba
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 440ee4d2-9c90-47a0-a2e7-9ec4d1a97683 # Data Imported
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e64964a8-80d4-4b6a-9ab9-46475c2e46bd
            userCondition: null
            warning: null
            width: 100
        name: Legacy
        uid: 5c1233cb-7f09-41e8-aac1-6ba8e1c2a758
        userCondition: null
handle: userResult
hasTitleField: true
name: 'User Result'
section: c0345752-9e56-4de1-a2d2-da641c3708e0 # Results
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 3
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
