fieldLayouts:
  457440da-2f23-4b47-8267-fcdfef51b254:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 14b8c677-a8a8-4df3-a74e-a30106bd5398
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 3ccae116-4500-45d0-a56a-024f2e8d4d03
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 5dd21124-5f28-49d6-8f3e-d70184415478
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 3cff7796-6519-48a5-97e7-e4dbb14befcc
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 2c8efd67-eb2c-40fd-b9d3-f660cc251a99
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Result
        sortOrder: 1
      -
        elements:
          -
            fieldUid: e7ff470a-3e85-47be-9037-1508ea540121
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: f7a6d059-9c07-4f32-a734-4bd9b5f2e210
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: c29bb59d-f545-409b-be92-c9b57e8cf603
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: d363cf24-3e53-4eea-b5f4-e9c72a3e9f65
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 06f9a436-94f4-4170-80ec-6e08d13115ee
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 53ded07f-6c81-4e7c-8e25-520b62d1a532
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 82f069e1-b11c-4e0d-96f6-eaf3e5d58387
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: d09c7ee9-90ad-4c7e-a8ec-a84e5f3457f0
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 295e5043-483c-4ad9-bfaa-bac22b99dc19
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 3103beed-feb4-4eed-b71a-68cb81d67f7e
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: a1d83c2a-d7f2-45d2-8430-7e2efd8d12ec
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Evidence
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 61e98c20-6536-4fb2-8420-7b21d34b4dd5
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Comments
        sortOrder: 3
      -
        elements:
          -
            fieldUid: a75d2fa6-54eb-4155-9483-d7729fb83004
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Custom Values'
        sortOrder: 4
      -
        elements:
          -
            fieldUid: 0b692c2e-5b0e-43b1-911a-f5052b808cf5
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 440ee4d2-9c90-47a0-a2e7-9ec4d1a97683
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Legacy
        sortOrder: 5
handle: userResult
hasTitleField: true
name: 'User Result'
section: c0345752-9e56-4de1-a2d2-da641c3708e0 # Results
sortOrder: 3
titleFormat: ''
