fieldLayouts:
  c4b22db3-609f-427d-b427-8b75e7bc7161:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5031e7e6-a77c-4557-a420-f1ecd733b057
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 92ccaa51-76c7-4264-982d-a778fe460342 # Auto Complete?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: edbc301d-e656-48df-b117-b96bdbdad327
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 31c31961-f4f1-4f09-9c8e-cbbd46d62e97 # Workflow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f4d49d3-75b5-41f9-9660-7ba3a83ce3c4
            userCondition: null
            warning: null
            width: 100
        name: 'Package Workflow'
        uid: 69a98925-34dc-4867-a751-82cfe09d54cb
        userCondition: null
handle: workflow
hasTitleField: true
name: Workflow
section: c0a51ffd-8054-40a9-824f-32657b83f14c # Taskbook Workflows
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
