tabs:
  -
    elements:
      -
        fieldUid: 4ac0fb06-5ba4-4129-ad0a-664727323d89 # User Company
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 50
      -
        fieldUid: ca3cc99a-ddf3-4e81-b35c-37d0ecd39ebb # User Team
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 50
      -
        fieldUid: dbbf1f49-3b86-4c6d-aa5a-4170483a35f1 # User Role
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 25
      -
        fieldUid: af392c27-30aa-4dde-a30c-fd69e3dd665e # Manager Level
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 25
      -
        fieldUid: e39c693b-aafd-4f9c-8e82-53aa5da6694e # User Read Only
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 25
      -
        fieldUid: 8df69537-0612-4b94-af60-c27617fddb4d # Manager Read Only
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 25
      -
        fieldUid: 6e432459-1ae7-4301-a7cd-e23c574bd569 # User Dummy Email
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 25
      -
        fieldUid: f5386b5d-29df-466e-a989-716777b0a655 # User Privacy
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 25
      -
        fieldUid: 3866c8e9-2a31-4ad0-bdd3-6cee13f90eb1 # User Privacy Date
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 25
    name: Structure
    sortOrder: 1
  -
    elements:
      -
        fieldUid: e0b2d8e4-6152-404e-b62c-e48c5d14cbb5 # User Not Licenced
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 50
      -
        fieldUid: e8e5de3b-79a6-4e11-ba75-6b78df9cc95f # User Licence Month
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 50
      -
        fieldUid: 67368df0-4936-4ba3-9b2a-82871f72d79d # User Licence Company
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 50
      -
        fieldUid: 27f36190-a4c4-4f11-b546-5e4ffb5efc06 # User Licence Source
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 50
    name: Licence
    sortOrder: 2
  -
    elements:
      -
        fieldUid: aa4a666c-db2c-4515-b356-344c43b82ca1 # User Start Date
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 25
      -
        fieldUid: f0039d1f-5cfd-4bf6-970e-5592f86712de # User Date of Birth
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 25
      -
        fieldUid: 041dc464-9e48-4a7d-9999-6cf36dd10aaa # User Expiry Date
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 25
      -
        type: craft\fieldlayoutelements\HorizontalRule
      -
        fieldUid: 0995325e-5dbc-4d5b-9582-a2457bd2a3c3 # User Type
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 25
      -
        fieldUid: d1847ab4-a98b-4069-b9db-3ef5cc3124f0 # User Company Name
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 75
      -
        fieldUid: 027f626e-2eaa-4fca-9665-c8812bce20a9 # User Address
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 100
      -
        fieldUid: e85a0c45-d4c3-4d25-81e6-80819d599872 # User Telephone
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 50
      -
        fieldUid: a15416ef-8183-4171-946e-fb80248cdc21 # User Membership Number
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 50
    name: Profile
    sortOrder: 3
  -
    elements:
      -
        fieldUid: f42b01d2-8bb4-4873-8c54-3def9f400a90 # User Taskbooks
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 50
      -
        fieldUid: 1f94c546-f86f-4989-841e-b7f45fb0cf4c # User Taskbook Companies
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 50
      -
        fieldUid: 7e30bff3-999f-48c7-b8aa-5f3498fba501 # External Companies
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 50
      -
        fieldUid: 6dba4616-7b94-4aa0-b8f2-a9f278b1ca8e # External Taskbooks
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 50
    name: 'Taskbook Reviews'
    sortOrder: 4
  -
    elements:
      -
        fieldUid: 7f1c4f49-327b-48eb-b631-5950532840c2 # User Payments
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 100
    name: Payments
    sortOrder: 5
  -
    elements:
      -
        fieldUid: 53b87ea0-021a-4671-bfbd-8000933bcf0e # User Custom Fields
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 100
    name: 'Custom Scheme User Fields'
    sortOrder: 6
  -
    elements:
      -
        fieldUid: dc88c84b-17f2-4b8b-8cc6-124b5115c9cc # Legacy ID
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 100
      -
        fieldUid: 3f2f2e5a-9c13-4199-aaa4-0d0d1eb8abfc # Legacy Company ID
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 100
      -
        fieldUid: 85884bff-7c6a-4759-a769-d3f056254b7b # Legacy Email
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 100
      -
        fieldUid: b7d6d158-4e92-4be7-ab53-c7e655c7e062 # Legacy Group
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 100
      -
        fieldUid: bb511299-1a44-4db4-b8f0-32035ca24b2d # Legacy Job Role ID
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 100
      -
        fieldUid: 31ce8d27-b2e8-42fd-90eb-c3365915c0be # Data Clean Managers Children
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 100
      -
        fieldUid: 080bb830-4bd6-458e-a3f3-dbb58358aeb1 # Data Clean Managers User Company
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 100
      -
        fieldUid: f6a57088-da9c-4ebb-ab25-070c60d329ea # Data Clean Job Role
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 100
      -
        fieldUid: 0ab87047-3af7-4556-92f5-2a8f396e025a # Data Clean Username
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 100
      -
        fieldUid: e0eca823-9419-4b9d-bbdb-e6161cc76f1c # Data Clean Password
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 100
      -
        fieldUid: fbb9f4ca-eb83-49d9-a5f0-b1a7996bf39c # Data Clean Result Cache
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 100
      -
        fieldUid: 440ee4d2-9c90-47a0-a2e7-9ec4d1a97683 # Data Imported
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 100
    name: Legacy
    sortOrder: 7
