tabs:
  -
    elementCondition: null
    elements:
      -
        elementCondition: null
        fieldUid: 4ac0fb06-5ba4-4129-ad0a-664727323d89 # User Company
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 92a19052-52bc-4122-ac2d-f3e8dcbe68e9
        userCondition: null
        warning: null
        width: 50
      -
        elementCondition: null
        fieldUid: ca3cc99a-ddf3-4e81-b35c-37d0ecd39ebb # User Team
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 5cd80798-1733-43d3-b10e-e220dbc51de0
        userCondition: null
        warning: null
        width: 50
      -
        elementCondition: null
        fieldUid: dbbf1f49-3b86-4c6d-aa5a-4170483a35f1 # User Role
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 0f2915ae-7493-4d52-8376-bb03e89e6a32
        userCondition: null
        warning: null
        width: 50
      -
        elementCondition: null
        fieldUid: aca49f37-5a2d-48d3-b0a3-793f13750dd4 # User Optional Modules
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 603585e0-e616-4dc2-91ef-29cf2900f433
        userCondition: null
        warning: null
        width: 50
      -
        elementCondition: null
        type: craft\fieldlayoutelements\HorizontalRule
        uid: 4639e680-6e33-46c4-94e3-3f3602d28e8e
        userCondition: null
      -
        elementCondition: null
        fieldUid: 58240fad-08ba-4e18-bc50-6a1ee991fb06 # User Linked User
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: dbb56855-bf5d-4de7-ad05-cb4d690b8b76
        userCondition: null
        warning: null
        width: 100
      -
        elementCondition: null
        type: craft\fieldlayoutelements\HorizontalRule
        uid: 20a8c235-c9d0-4130-957e-799c191e1089
        userCondition: null
      -
        elementCondition: null
        fieldUid: af392c27-30aa-4dde-a30c-fd69e3dd665e # Manager Level
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: d5678980-e23b-4e2d-a6b2-3e376cffd09b
        userCondition: null
        warning: null
        width: 25
      -
        elementCondition: null
        fieldUid: e39c693b-aafd-4f9c-8e82-53aa5da6694e # User Read Only
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: ba679ebd-cd74-470a-a636-465ed3347187
        userCondition: null
        warning: null
        width: 25
      -
        elementCondition: null
        fieldUid: 8df69537-0612-4b94-af60-c27617fddb4d # Manager Read Only
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 8becec53-912b-4f4e-a584-f89e47df1466
        userCondition: null
        warning: null
        width: 25
      -
        elementCondition: null
        fieldUid: 6e432459-1ae7-4301-a7cd-e23c574bd569 # User Dummy Email
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 1a6c4bd7-de1a-4a20-b3fb-e36b3da3e657
        userCondition: null
        warning: null
        width: 25
      -
        elementCondition: null
        type: craft\fieldlayoutelements\HorizontalRule
        uid: 025ba100-1b95-4616-a053-408cfd816593
        userCondition: null
      -
        elementCondition: null
        fieldUid: f5386b5d-29df-466e-a989-716777b0a655 # User Privacy
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 6e4c8b98-8eef-4298-9191-185effb5f141
        userCondition: null
        warning: null
        width: 25
      -
        elementCondition: null
        fieldUid: 3866c8e9-2a31-4ad0-bdd3-6cee13f90eb1 # User Privacy Date
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: f6f43a8b-6013-4e0c-a7e6-9a85d6fb00ec
        userCondition: null
        warning: null
        width: 25
    name: Structure
    uid: a6ce52db-ee41-435f-afa5-e45268ea93e8
    userCondition: null
  -
    elementCondition: null
    elements:
      -
        elementCondition: null
        fieldUid: e0b2d8e4-6152-404e-b62c-e48c5d14cbb5 # User Not Licenced
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: a8734c38-ffee-45e0-a6e3-a1841e7bd6d5
        userCondition: null
        warning: null
        width: 50
      -
        elementCondition: null
        fieldUid: e8e5de3b-79a6-4e11-ba75-6b78df9cc95f # User Licence Month
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 9c88e4a4-5e5c-4fa1-8942-cd6f9da73894
        userCondition: null
        warning: null
        width: 50
      -
        elementCondition: null
        fieldUid: 12871de0-f772-46c9-a3e4-d4d6578bc35f # User Licence ID
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: c04c686c-6e8b-4665-92ab-2aa535d49354
        userCondition: null
        warning: null
        width: 50
      -
        elementCondition: null
        fieldUid: 67368df0-4936-4ba3-9b2a-82871f72d79d # User Licence Company
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: ecfe896a-8f85-4c9c-8554-269e9545f3e4
        userCondition: null
        warning: null
        width: 50
    name: Licence
    uid: 302b446e-9707-446c-8248-cdb97eb6b30f
    userCondition: null
  -
    elementCondition: null
    elements:
      -
        elementCondition: null
        fieldUid: aa4a666c-db2c-4515-b356-344c43b82ca1 # User Start Date
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 1e115687-25d2-4e5f-8ded-6c55ecf4c6a4
        userCondition: null
        warning: null
        width: 25
      -
        elementCondition: null
        fieldUid: f0039d1f-5cfd-4bf6-970e-5592f86712de # User Date of Birth
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 39dfdc3a-03b9-458d-8358-7e75a3567808
        userCondition: null
        warning: null
        width: 25
      -
        elementCondition: null
        fieldUid: 041dc464-9e48-4a7d-9999-6cf36dd10aaa # User Expiry Date
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: b40ab919-b78f-437a-aa6f-d68e143b968b
        userCondition: null
        warning: null
        width: 25
      -
        elementCondition: null
        type: craft\fieldlayoutelements\HorizontalRule
        uid: 922e0465-35bd-478e-aaa1-0b57dbc9208b
        userCondition: null
      -
        elementCondition: null
        fieldUid: 0995325e-5dbc-4d5b-9582-a2457bd2a3c3 # User Type
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 6e32f5d8-1ddf-4842-b7a3-bf2641ea738a
        userCondition: null
        warning: null
        width: 25
      -
        elementCondition: null
        fieldUid: d1847ab4-a98b-4069-b9db-3ef5cc3124f0 # User Company Name
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 962a67e0-455d-4362-b3d0-b8ed10cb2165
        userCondition: null
        warning: null
        width: 75
      -
        elementCondition: null
        fieldUid: 027f626e-2eaa-4fca-9665-c8812bce20a9 # User Address
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 4c1a5466-c981-4ab3-8064-1a4684952b14
        userCondition: null
        warning: null
        width: 100
      -
        elementCondition: null
        fieldUid: e85a0c45-d4c3-4d25-81e6-80819d599872 # User Telephone
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 7911db46-5b55-4cac-aed1-07ac05987f32
        userCondition: null
        warning: null
        width: 50
      -
        elementCondition: null
        fieldUid: a15416ef-8183-4171-946e-fb80248cdc21 # User Membership Number
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 7c84a681-7578-42bc-8426-5ef220847f67
        userCondition: null
        warning: null
        width: 50
    name: Profile
    uid: 5cbba6d7-6698-4870-995d-21c48b004f3b
    userCondition: null
  -
    elementCondition: null
    elements:
      -
        elementCondition: null
        fieldUid: f42b01d2-8bb4-4873-8c54-3def9f400a90 # User Taskbooks
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: c567bcb4-f6e3-4673-86ea-b1e15476fe68
        userCondition: null
        warning: null
        width: 50
      -
        elementCondition: null
        fieldUid: 1f94c546-f86f-4989-841e-b7f45fb0cf4c # User Taskbook Companies
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 1c95e97e-0225-46a9-b3b7-dc87ef8c4627
        userCondition: null
        warning: null
        width: 50
      -
        elementCondition: null
        fieldUid: 7e30bff3-999f-48c7-b8aa-5f3498fba501 # External Companies
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: ec9787bd-90b2-4aef-a32b-5e8f12f55dff
        userCondition: null
        warning: null
        width: 50
      -
        elementCondition: null
        fieldUid: 6dba4616-7b94-4aa0-b8f2-a9f278b1ca8e # External Taskbooks
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 093c72e9-5404-4080-9209-d905616b5646
        userCondition: null
        warning: null
        width: 50
    name: 'Taskbook Reviews'
    uid: 7eb99f80-0ac5-4628-a9b0-2b94c6f4d974
    userCondition: null
  -
    elementCondition: null
    elements:
      -
        elementCondition: null
        fieldUid: 352c0bfb-8be5-46ba-88e6-d2882d2f4d75 # Base Payments
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: e433ce1f-9029-424b-b87e-e9fde0beceec
        userCondition: null
        warning: null
        width: 100
      -
        elementCondition: null
        fieldUid: 7f1c4f49-327b-48eb-b631-5950532840c2 # User Payments
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: eaabb6bf-783f-4e2d-bac6-6dca5fceebf1
        userCondition: null
        warning: null
        width: 100
    name: Payments
    uid: 663102f1-5166-4387-8745-7b2c25f450e8
    userCondition: null
  -
    elementCondition: null
    elements:
      -
        elementCondition: null
        fieldUid: 53b87ea0-021a-4671-bfbd-8000933bcf0e # Custom Fields
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 19f99e00-55e0-49c3-99c5-abbb2c10ac4b
        userCondition: null
        warning: null
        width: 100
    name: 'Custom Fields'
    uid: 15fe21cb-00e4-4f8b-a36b-71545fc31451
    userCondition: null
  -
    elementCondition: null
    elements:
      -
        elementCondition: null
        fieldUid: dc88c84b-17f2-4b8b-8cc6-124b5115c9cc # Legacy ID
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 6c559d95-b0f1-4a1f-87f7-f4b09349c4f0
        userCondition: null
        warning: null
        width: 100
      -
        elementCondition: null
        fieldUid: 3f2f2e5a-9c13-4199-aaa4-0d0d1eb8abfc # Legacy Company ID
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: b29cf58b-0d05-44c7-8f9d-796e13803d57
        userCondition: null
        warning: null
        width: 100
      -
        elementCondition: null
        fieldUid: 85884bff-7c6a-4759-a769-d3f056254b7b # Legacy Email
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 5b4d3430-eff3-4e9c-97c2-132043bc20fd
        userCondition: null
        warning: null
        width: 100
      -
        elementCondition: null
        fieldUid: b7d6d158-4e92-4be7-ab53-c7e655c7e062 # Legacy Group
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 826ae157-430b-48ac-9159-ac3ab968db3a
        userCondition: null
        warning: null
        width: 100
      -
        elementCondition: null
        fieldUid: bb511299-1a44-4db4-b8f0-32035ca24b2d # Legacy Job Role ID
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 33a1e5cd-f90c-4ede-814e-b12d7ae5df41
        userCondition: null
        warning: null
        width: 100
      -
        elementCondition: null
        fieldUid: 31ce8d27-b2e8-42fd-90eb-c3365915c0be # Data Clean Managers Children
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: fbf917f2-1dec-490e-a881-5258cfc416fb
        userCondition: null
        warning: null
        width: 100
      -
        elementCondition: null
        fieldUid: 080bb830-4bd6-458e-a3f3-dbb58358aeb1 # Data Clean Managers User Company
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 2ccc2771-3cc9-4546-9213-9522a0b7c58c
        userCondition: null
        warning: null
        width: 100
      -
        elementCondition: null
        fieldUid: f6a57088-da9c-4ebb-ab25-070c60d329ea # Data Clean Job Role
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: b454eccc-6627-4658-a0bc-13220355eb9a
        userCondition: null
        warning: null
        width: 100
      -
        elementCondition: null
        fieldUid: 0ab87047-3af7-4556-92f5-2a8f396e025a # Data Clean Username
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 76631bc2-981c-4133-a580-97d28247c0df
        userCondition: null
        warning: null
        width: 100
      -
        elementCondition: null
        fieldUid: e0eca823-9419-4b9d-bbdb-e6161cc76f1c # Data Clean Password
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: ab729552-9ef6-4181-a3d6-052d2e0caaae
        userCondition: null
        warning: null
        width: 100
      -
        elementCondition: null
        fieldUid: fbb9f4ca-eb83-49d9-a5f0-b1a7996bf39c # Data Clean Result Cache
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 472f7609-cb13-47a0-8d8f-a61e230eadd2
        userCondition: null
        warning: null
        width: 100
      -
        elementCondition: null
        fieldUid: 440ee4d2-9c90-47a0-a2e7-9ec4d1a97683 # Data Imported
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 2491b99e-039b-47a5-8ef2-b3326b1c8cc2
        userCondition: null
        warning: null
        width: 100
    name: Legacy
    uid: 38b2fc43-6e50-430e-9c54-4d54a9b5a2a2
    userCondition: null
