field: 4b25bd1b-f51c-4175-8db7-e871de866f2f
fieldLayouts:
  b6774e86-2d02-4f1e-8fcc-df899659d76c:
    tabs:
      -
        fields:
          3a779dd7-470c-4c09-9363-7f1be3a04a59:
            required: false
            sortOrder: 1
          09efb818-9488-45a7-b860-1fc9d3c99155:
            required: false
            sortOrder: 2
          57ccb83f-5e54-480a-90b7-e80dfbc8cc94:
            required: false
            sortOrder: 4
          c7ee8208-f166-48c8-b7c2-e8eab9555b64:
            required: false
            sortOrder: 3
        name: Content
        sortOrder: 1
fields:
  3a779dd7-470c-4c09-9363-7f1be3a04a59:
    contentColumnType: integer(10)
    fieldGroup: null
    handle: questionId
    instructions: ''
    name: 'Question ID'
    searchable: true
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: '0'
      prefix: null
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  09efb818-9488-45a7-b860-1fc9d3c99155:
    contentColumnType: text
    fieldGroup: null
    handle: question
    instructions: ''
    name: Question
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  57ccb83f-5e54-480a-90b7-e80dfbc8cc94:
    contentColumnType: boolean
    fieldGroup: null
    handle: correct
    instructions: ''
    name: Correct
    searchable: true
    settings:
      default: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  c7ee8208-f166-48c8-b7c2-e8eab9555b64:
    contentColumnType: text
    fieldGroup: null
    handle: answer
    instructions: ''
    name: Answer
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: answer
name: Answer
sortOrder: 1
