field: b8c430cf-c3d3-4d15-a8a8-21eb2fb94ace # Content
fieldLayouts:
  33a2cd8b-939a-4112-af78-f861c965887f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 56f0758a-86e6-4c78-ae70-e09843a275a2 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f7091b99-09ec-491f-93ad-8b626d0a09d9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9a8e1aa6-c705-41e6-ab80-8c987022d24b # HTML
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a76f51b8-0b5b-4621-bc17-ebf53e589ec5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 897563b3-c12c-47c5-9c93-fa7d03b684f4
        userCondition: null
fields:
  9a8e1aa6-c705-41e6-ab80-8c987022d24b: # HTML
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: columnHtml
    instructions: null
    name: HTML
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes:
        - f6dc0b30-2f16-4c2d-ad2e-849d3de5d0f9 # Uploads
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: false
      redactorConfig: Standard.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  56f0758a-86e6-4c78-ae70-e09843a275a2: # Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: columnTitle
    instructions: null
    name: Title
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: columns
name: Columns
sortOrder: 1
