field: 53b87ea0-021a-4671-bfbd-8000933bcf0e # Custom Fields
fieldLayouts:
  d7aeffce-740a-42a3-b581-cd245fa7934c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 03b567a4-41fe-44fc-8b41-a896abbe328f # Custom Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 82b6784c-c9d7-47e2-8d5a-64037a985e12
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e4cbe147-47ff-4ad4-845e-cc788f8b8829 # Custom Value
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a0b4f25f-eb79-4808-bb29-d6799f6d8037
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6d9b7444-0767-40a0-8954-b3f95cce174d
        userCondition: null
fields:
  03b567a4-41fe-44fc-8b41-a896abbe328f: # Custom Name
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: customName
    instructions: null
    name: 'Custom Name'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e4cbe147-47ff-4ad4-845e-cc788f8b8829: # Custom Value
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: customValue
    instructions: null
    name: 'Custom Value'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: customField
name: 'Custom Field'
sortOrder: 1
