field: 7f1c4f49-327b-48eb-b631-5950532840c2 # User Payments
fieldLayouts:
  aca00fb2-fff5-4778-bbcb-48193d2a64ec:
    tabs:
      -
        elements:
          -
            fieldUid: 70223568-9924-4df6-a581-7134a87dc443 # Payer Email
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0507fd56-62a9-42b1-a4ce-7f5e221df8a2 # Payment Amount
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c82b9786-ae99-4b9d-89ef-a97b92d4366d # Transaction ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8e163b19-5447-4841-852c-c7c3ba58f29e # Synced To Base
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  8e163b19-5447-4841-852c-c7c3ba58f29e: # Synced To Base
    columnSuffix: fmepwveg
    contentColumnType: boolean
    fieldGroup: null
    handle: syncedToBase
    instructions: ''
    name: 'Synced To Base'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  0507fd56-62a9-42b1-a4ce-7f5e221df8a2: # Payment Amount
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: mc_gross
    instructions: ''
    name: 'Payment Amount'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  70223568-9924-4df6-a581-7134a87dc443: # Payer Email
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: payer_email
    instructions: ''
    name: 'Payer Email'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c82b9786-ae99-4b9d-89ef-a97b92d4366d: # Transaction ID
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: txn_id
    instructions: ''
    name: 'Transaction ID'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: paypal
name: PayPal
sortOrder: 1
