field: 7f1c4f49-327b-48eb-b631-5950532840c2 # User Payments
fieldLayouts:
  aca00fb2-fff5-4778-bbcb-48193d2a64ec:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 70223568-9924-4df6-a581-7134a87dc443 # Payer Email
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 288d23b7-eb43-427b-8410-c5c8612bff6e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0507fd56-62a9-42b1-a4ce-7f5e221df8a2 # Payment Amount
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f8e447de-6c61-40a9-bc73-c3f47b3b203f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c82b9786-ae99-4b9d-89ef-a97b92d4366d # Transaction ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f427bdf3-c32e-423e-8a46-bc5dde46c3e9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8e163b19-5447-4841-852c-c7c3ba58f29e # Synced To Base
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b2358193-dbfe-4d20-92db-f8de3c619fe1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 03afa7f3-8206-4936-bca0-2374564f9520
        userCondition: null
fields:
  8e163b19-5447-4841-852c-c7c3ba58f29e: # Synced To Base
    columnSuffix: fmepwveg
    contentColumnType: boolean
    fieldGroup: null
    handle: syncedToBase
    instructions: null
    name: 'Synced To Base'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  0507fd56-62a9-42b1-a4ce-7f5e221df8a2: # Payment Amount
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: mc_gross
    instructions: null
    name: 'Payment Amount'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  70223568-9924-4df6-a581-7134a87dc443: # Payer Email
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: payer_email
    instructions: null
    name: 'Payer Email'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c82b9786-ae99-4b9d-89ef-a97b92d4366d: # Transaction ID
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: txn_id
    instructions: null
    name: 'Transaction ID'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: paypal
name: PayPal
sortOrder: 1
