field: 4a4bc5cd-115e-4309-a51a-3e5095ceea90 # Home Slider
fieldLayouts:
  d3af77e8-adbb-403d-8ca0-78f119435628:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 111e6e76-917a-43f6-aa70-c659bd131921 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c2ce1393-2c54-41f0-8d43-a9f6f523e1bb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4978c00f-2afb-4601-83f2-12952bc08242 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4ebdedd3-c1f4-4694-9b16-a568067550e9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2558296b-ca8b-4d67-b227-6310a19405da # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: da9a6b5c-3aea-4cce-b9a3-d0f197efd059
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 89bc5035-7e58-43a7-a7e5-bcaa9de73d4a # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 300b8ab1-2982-4e4b-9e51-06cf3cd51dec
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 09cb3567-5330-4f9c-92b0-3e085c2a5099
        userCondition: null
fields:
  89bc5035-7e58-43a7-a7e5-bcaa9de73d4a: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: slideImage
    instructions: null
    name: Image
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:a6dafdf7-e4c0-4943-aff3-e481bbdf23fc' # Evidence
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:f2ee622f-5058-4e7d-a3d0-1d003dc32c29' # Theme
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  111e6e76-917a-43f6-aa70-c659bd131921: # Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: slideTitle
    instructions: null
    name: Title
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  4978c00f-2afb-4601-83f2-12952bc08242: # Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: slideHeading
    instructions: null
    name: Heading
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  2558296b-ca8b-4d67-b227-6310a19405da: # Content
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: slideContent
    instructions: null
    name: Content
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: slide
name: Slide
sortOrder: 1
