field: 6f94bf9b-3168-437e-b8f2-7d082dcdd831 # Unit Groups
fieldLayouts:
  11bf57e1-f8b5-4045-9861-210b0d80c82b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 45d289dd-249a-42e9-95ae-62ab979e8b02 # Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 622d871d-1790-44b4-9337-6f64052f3ddf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: de561917-2808-45e4-b7db-324c21a2aebf # Notes
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0694dc92-ee8f-48be-8d02-ec29e6b648ec
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a773e69f-0bf1-46fd-ae75-5182be37772c # Unit Entries
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 579d53e2-99d9-4967-a5e2-73e7c470f472
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1a03c2db-7359-4f1c-8ed2-3de20e4fd7e9 # Enable Multiple Results?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a9f112f-3371-4ccd-8331-d6726d590b8f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 46656fa8-cf4d-4c7e-93d0-800132d01aa2 # Unit Points Override
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 36ad176d-e682-402c-836c-63be35af92b9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7b47144d-bd9e-4b97-bd0c-6b7ff206d9e0 # CPD Target Points
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 31f6040a-e6e8-4369-b2b4-b8ce08adaabd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 64769feb-a327-4c92-8224-bfd94a529f1a # CPD Target Hours
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6f0277f1-0bf0-4951-b625-c2ac8c702f1a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9e0cc206-144e-4e94-a034-a85e274e2323
        userCondition: null
fields:
  1a03c2db-7359-4f1c-8ed2-3de20e4fd7e9: # Enable Multiple Results?
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: enableSubmissions
    instructions: null
    name: 'Enable Multiple Results?'
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  7b47144d-bd9e-4b97-bd0c-6b7ff206d9e0: # CPD Target Points
    columnSuffix: null
    contentColumnType: integer(10)
    fieldGroup: null
    handle: cpdTargetPoints
    instructions: 'Only for CPD type modules - must be met to complete this unit group.'
    name: 'CPD Target Points'
    searchable: true
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: Points
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  45d289dd-249a-42e9-95ae-62ab979e8b02: # Name
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: groupName
    instructions: null
    name: Name
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  46656fa8-cf4d-4c7e-93d0-800132d01aa2: # Unit Points Override
    columnSuffix: null
    contentColumnType: integer(10)
    fieldGroup: null
    handle: unitPointsOverride
    instructions: 'Set all units in this group to the same point value.'
    name: 'Unit Points Override'
    searchable: true
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  64769feb-a327-4c92-8224-bfd94a529f1a: # CPD Target Hours
    columnSuffix: null
    contentColumnType: integer(10)
    fieldGroup: null
    handle: cpdTargetHours
    instructions: 'Only for CPD type modules - must be met to complete this unit group.'
    name: 'CPD Target Hours'
    searchable: true
    settings:
      decimals: 0
      defaultValue: 0
      max: null
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: Hours
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  a773e69f-0bf1-46fd-ae75-5182be37772c: # Unit Entries
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: unitEntries
    instructions: null
    name: 'Unit Entries'
    searchable: true
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionLabel: null
      showSiteMenu: true
      sources:
        - 'section:090b3c24-a9ac-4935-a919-c4fc8a3099b0' # Units
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  de561917-2808-45e4-b7db-324c21a2aebf: # Notes
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: groupNotes
    instructions: null
    name: Notes
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: unitGroup
name: 'Unit Group'
sortOrder: 1
