field: edcdcb64-8b0b-4f31-ab57-106c9e252317 # Package Module Groups
fieldLayouts:
  1fec76e6-301b-49d2-a65d-7e7589e07374:
    tabs:
      -
        fields:
          00afc899-b37a-415c-8829-b06a42a8638f: # Module Group
            required: '1'
            sortOrder: '1'
          8b738285-1f1f-4f66-bb77-bdf61a7f234e: # Mandatory
            required: '0'
            sortOrder: '2'
          9a61af4b-dccb-4d5e-9bc1-53b775f9de18: # Level
            required: '1'
            sortOrder: '3'
          7209f99b-e88b-403f-b8ba-fbb0301b5c0f: # Paid
            required: '0'
            sortOrder: '4'
          cad6f0cc-99c2-432e-b299-3990a84d96fc: # Cost
            required: '0'
            sortOrder: '5'
        name: Content
        sortOrder: '1'
fields:
  00afc899-b37a-415c-8829-b06a42a8638f: # Module Group
    contentColumnType: string
    fieldGroup: null
    handle: moduleGroup
    instructions: ''
    name: 'Module Group'
    searchable: '1'
    settings:
      allowLimit: false
      allowMultipleSources: false
      allowSelfRelations: ''
      branchLimit: '1'
      limit: null
      localizeRelations: false
      selectionLabel: 'Select module group'
      source: 'group:98a87e5b-9324-4727-ab66-b99bfdccbc68' # Module Groups
      sources: '*'
      targetSiteId: null
      validateRelatedElements: ''
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Categories
  8b738285-1f1f-4f66-bb77-bdf61a7f234e: # Mandatory
    contentColumnType: boolean
    fieldGroup: null
    handle: moduleGroupMandatory
    instructions: ''
    name: Mandatory
    searchable: '1'
    settings:
      default: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  9a61af4b-dccb-4d5e-9bc1-53b775f9de18: # Level
    contentColumnType: smallint(2)
    fieldGroup: null
    handle: moduleGroupLevel
    instructions: ''
    name: Level
    searchable: '1'
    settings:
      decimals: 0
      defaultValue: '1'
      max: '10'
      min: '1'
      prefix: ''
      size: null
      suffix: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  7209f99b-e88b-403f-b8ba-fbb0301b5c0f: # Paid
    contentColumnType: boolean
    fieldGroup: null
    handle: moduleGroupPaid
    instructions: ''
    name: Paid
    searchable: '1'
    settings:
      default: '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  cad6f0cc-99c2-432e-b299-3990a84d96fc: # Cost
    contentColumnType: integer(10)
    fieldGroup: null
    handle: moduleGroupCost
    instructions: ''
    name: Cost
    searchable: '1'
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: '0'
      prefix: ''
      size: null
      suffix: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
