field: edcdcb64-8b0b-4f31-ab57-106c9e252317
fieldLayouts:
  1fec76e6-301b-49d2-a65d-7e7589e07374:
    tabs:
      -
        fields:
          00afc899-b37a-415c-8829-b06a42a8638f:
            required: '1'
            sortOrder: '1'
          9a61af4b-dccb-4d5e-9bc1-53b775f9de18:
            required: '1'
            sortOrder: '2'
        name: Content
        sortOrder: '1'
fields:
  00afc899-b37a-415c-8829-b06a42a8638f:
    contentColumnType: string
    fieldGroup: null
    handle: optionalTaskbookGroup
    instructions: ''
    name: 'Taskbook Group'
    searchable: '1'
    settings:
      allowLimit: false
      allowMultipleSources: false
      branchLimit: '1'
      limit: null
      localizeRelations: false
      selectionLabel: 'Select optional taskbook group'
      source: 'group:a8731481-f6d5-4f6e-9d29-0bd442774b61'
      sources: '*'
      targetSiteId: null
      validateRelatedElements: ''
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Categories
  9a61af4b-dccb-4d5e-9bc1-53b775f9de18:
    contentColumnType: smallint(2)
    fieldGroup: null
    handle: optionalLevel
    instructions: ''
    name: Level
    searchable: '1'
    settings:
      decimals: 0
      defaultValue: '1'
      max: '10'
      min: '1'
      prefix: ''
      size: null
      suffix: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
