changedFieldIndicator: null
field: a75d2fa6-54eb-4155-9483-d7729fb83004 # Result Custom
fieldLayouts:
  92c764d5-c74d-44b3-aa9e-73abc60aecc1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5f11fa33-3356-44d4-ad91-0b9ca0ad5f6b # Custom Key
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 55f3c283-f9a6-4db0-8386-cb765bb2f713
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 70a4b8f2-f454-40e6-82d7-ff577995e2a4 # Custom Value
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 23942b71-5228-4e6f-ab56-98cc97fe99c7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 179125e7-adb0-4144-a984-f710f1afe079
        userCondition: null
fields:
  5f11fa33-3356-44d4-ad91-0b9ca0ad5f6b: # Custom Key
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: customKey
    instructions: null
    name: 'Custom Key'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  70a4b8f2-f454-40e6-82d7-ff577995e2a4: # Custom Value
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: customValue
    instructions: null
    name: 'Custom Value'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
