field: a75d2fa6-54eb-4155-9483-d7729fb83004 # Result Custom
fieldLayouts:
  92c764d5-c74d-44b3-aa9e-73abc60aecc1:
    tabs:
      -
        fields:
          5f11fa33-3356-44d4-ad91-0b9ca0ad5f6b: # Custom Key
            required: '0'
            sortOrder: '1'
          70a4b8f2-f454-40e6-82d7-ff577995e2a4: # Custom Value
            required: '0'
            sortOrder: '2'
        name: Content
        sortOrder: '1'
fields:
  5f11fa33-3356-44d4-ad91-0b9ca0ad5f6b: # Custom Key
    contentColumnType: text
    fieldGroup: null
    handle: customKey
    instructions: ''
    name: 'Custom Key'
    searchable: '1'
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  70a4b8f2-f454-40e6-82d7-ff577995e2a4: # Custom Value
    contentColumnType: text
    fieldGroup: null
    handle: customValue
    instructions: ''
    name: 'Custom Value'
    searchable: '1'
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
