field: bfce8aaa-028f-4d73-8f1d-20ba8f5a871b # Column Layout
fieldLayouts:
  bc118b5e-ef7a-4c5c-9c98-6879c1a89a21:
    tabs:
      -
        elements:
          -
            fieldUid: 8fec0242-3542-431e-8a9a-d2d86b3e3b06 # Field Type
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 19794a8d-aa57-4cea-9297-7c4ccfb2d561 # Field Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 31a1729c-6625-4e9e-9ffe-3fcce0da9bbd # Field Manager Only
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 74329152-64bf-43a9-95b3-0458edd36e4f # Field Custom Key
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6cb593e0-eb38-45a0-bd9b-22a23586dfbe # Field Custom Type
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a37728d1-3a88-46ca-b9d5-ec79b66ba635 # Field Custom Options
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7ed267ff-a262-4e68-81b8-be3bcaa5c178 # Field Required
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b46f9aa2-ceed-4dee-ac99-835a93962438 # Field Display
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  6cb593e0-eb38-45a0-bd9b-22a23586dfbe: # Field Custom Type
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: fieldCustomType
    instructions: ''
    name: 'Field Custom Type'
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - default
              - '1'
            -
              - label
              - Text
            -
              - value
              - text
        -
          __assoc__:
            -
              - default
              - ''
            -
              - label
              - Dropdown
            -
              - value
              - dropdown
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  7ed267ff-a262-4e68-81b8-be3bcaa5c178: # Field Required
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: fieldRequired
    instructions: ''
    name: 'Field Required'
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  8fec0242-3542-431e-8a9a-d2d86b3e3b06: # Field Type
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: fieldType
    instructions: ''
    name: 'Field Type'
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - default
              - ''
            -
              - label
              - Type
            -
              - value
              - unitType
        -
          __assoc__:
            -
              - default
              - ''
            -
              - label
              - 'Unit Points'
            -
              - value
              - unitPoints
        -
          __assoc__:
            -
              - default
              - ''
            -
              - label
              - Status
            -
              - value
              - resultStatus
        -
          __assoc__:
            -
              - default
              - ''
            -
              - label
              - 'Endorsed Date'
            -
              - value
              - resultEndorsedDate
        -
          __assoc__:
            -
              - default
              - ''
            -
              - label
              - 'Endorsed User'
            -
              - value
              - resultEndorsedUser
        -
          __assoc__:
            -
              - default
              - ''
            -
              - label
              - 'Expiry Date'
            -
              - value
              - resultExpiryDate
        -
          __assoc__:
            -
              - default
              - ''
            -
              - label
              - 'Start Date'
            -
              - value
              - resultStartDate
        -
          __assoc__:
            -
              - default
              - ''
            -
              - label
              - 'Finish Date'
            -
              - value
              - resultFinishDate
        -
          __assoc__:
            -
              - default
              - ''
            -
              - label
              - Location
            -
              - value
              - resultLocation
        -
          __assoc__:
            -
              - default
              - ''
            -
              - label
              - Evidence
            -
              - value
              - resultEvidence
        -
          __assoc__:
            -
              - default
              - ''
            -
              - label
              - Custom
            -
              - value
              - resultCustom
        -
          __assoc__:
            -
              - default
              - ''
            -
              - label
              - 'Result Points'
            -
              - value
              - resultPoints
        -
          __assoc__:
            -
              - default
              - ''
            -
              - label
              - 'Result Hours'
            -
              - value
              - resultHours
        -
          __assoc__:
            -
              - default
              - ''
            -
              - label
              - 'Result Narrative'
            -
              - value
              - resultNarrative
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  31a1729c-6625-4e9e-9ffe-3fcce0da9bbd: # Field Manager Only
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: fieldManagerOnly
    instructions: ''
    name: 'Field Manager Only'
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  19794a8d-aa57-4cea-9297-7c4ccfb2d561: # Field Label
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: fieldLabel
    instructions: ''
    name: 'Field Label'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  74329152-64bf-43a9-95b3-0458edd36e4f: # Field Custom Key
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: fieldCustomKey
    instructions: ''
    name: 'Field Custom Key'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a37728d1-3a88-46ca-b9d5-ec79b66ba635: # Field Custom Options
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: fieldCustomOptions
    instructions: ''
    name: 'Field Custom Options'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b46f9aa2-ceed-4dee-ac99-835a93962438: # Field Display
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: fieldDisplay
    instructions: ''
    name: 'Field Display'
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - default
              - '1'
            -
              - label
              - Both
            -
              - value
              - both
        -
          __assoc__:
            -
              - default
              - ''
            -
              - label
              - Table
            -
              - value
              - table
        -
          __assoc__:
            -
              - default
              - ''
            -
              - label
              - Form
            -
              - value
              - form
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
