changedFieldIndicator: null
field: bfce8aaa-028f-4d73-8f1d-20ba8f5a871b # Column Layout
fieldLayouts:
  bc118b5e-ef7a-4c5c-9c98-6879c1a89a21:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8fec0242-3542-431e-8a9a-d2d86b3e3b06 # Field Type
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e92b8df5-f00e-4893-a455-01b118bff027
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 19794a8d-aa57-4cea-9297-7c4ccfb2d561 # Field Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b67aa5a6-d760-4c1b-a231-460044a41968
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 31a1729c-6625-4e9e-9ffe-3fcce0da9bbd # Field Manager Only
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4371c823-f6d1-41a2-a559-1e2845562848
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 74329152-64bf-43a9-95b3-0458edd36e4f # Field Custom Key
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 452d1e71-bb74-46cb-a499-1b7f20e0865d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6cb593e0-eb38-45a0-bd9b-22a23586dfbe # Field Custom Type
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aa157816-6f67-4ead-8f7b-b6d0550c3580
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a37728d1-3a88-46ca-b9d5-ec79b66ba635 # Field Custom Options
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 52021d4a-a41a-4d5e-a42b-62c247ed747f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7ed267ff-a262-4e68-81b8-be3bcaa5c178 # Field Required
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f0d1307f-bf67-4d2d-8d0c-7594c8daeed9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b46f9aa2-ceed-4dee-ac99-835a93962438 # Field Display
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 11270cd5-9476-41eb-82df-74823c8b6765
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9400b1de-de3e-4016-8900-4170e52e8599
        userCondition: null
fields:
  6cb593e0-eb38-45a0-bd9b-22a23586dfbe: # Field Custom Type
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: fieldCustomType
    instructions: null
    name: 'Field Custom Type'
    searchable: true
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - Text
            -
              - value
              - text
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Dropdown
            -
              - value
              - dropdown
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  7ed267ff-a262-4e68-81b8-be3bcaa5c178: # Field Required
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: fieldRequired
    instructions: null
    name: 'Field Required'
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  8fec0242-3542-431e-8a9a-d2d86b3e3b06: # Field Type
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: fieldType
    instructions: null
    name: 'Field Type'
    searchable: true
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - Type
            -
              - value
              - unitType
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Unit Points'
            -
              - value
              - unitPoints
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Status
            -
              - value
              - resultStatus
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Endorsed Date'
            -
              - value
              - resultEndorsedDate
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Endorsed User'
            -
              - value
              - resultEndorsedUser
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Expiry Date'
            -
              - value
              - resultExpiryDate
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Start Date'
            -
              - value
              - resultStartDate
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Finish Date'
            -
              - value
              - resultFinishDate
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Location
            -
              - value
              - resultLocation
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Evidence
            -
              - value
              - resultEvidence
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Custom
            -
              - value
              - resultCustom
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Result Points'
            -
              - value
              - resultPoints
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Result Hours'
            -
              - value
              - resultHours
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Result Narrative'
            -
              - value
              - resultNarrative
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Result Outcome'
            -
              - value
              - resultOutcome
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  31a1729c-6625-4e9e-9ffe-3fcce0da9bbd: # Field Manager Only
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: fieldManagerOnly
    instructions: null
    name: 'Field Manager Only'
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  19794a8d-aa57-4cea-9297-7c4ccfb2d561: # Field Label
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: fieldLabel
    instructions: null
    name: 'Field Label'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  74329152-64bf-43a9-95b3-0458edd36e4f: # Field Custom Key
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: fieldCustomKey
    instructions: null
    name: 'Field Custom Key'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a37728d1-3a88-46ca-b9d5-ec79b66ba635: # Field Custom Options
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: fieldCustomOptions
    instructions: null
    name: 'Field Custom Options'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b46f9aa2-ceed-4dee-ac99-835a93962438: # Field Display
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: fieldDisplay
    instructions: null
    name: 'Field Display'
    searchable: true
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - Both
            -
              - value
              - both
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Table
            -
              - value
              - table
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Form
            -
              - value
              - form
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
