changedFieldIndicator: null
field: 61e98c20-6536-4fb2-8420-7b21d34b4dd5 # Result Comments
fieldLayouts:
  21ce6d78-5c1b-4d6b-84b6-73b6b453d065:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0c515fa0-cbdd-4bd9-8267-917a447e5702 # User
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: afaa9c67-4c9b-4524-83bd-a00b43c554d5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3c50a00d-c61b-4018-bed4-f1685a215e01 # Comment
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8d08b47c-7dc3-4141-82fd-63bd84cfd72e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cea55199-bbc5-4529-8451-c12a00ff1080 # Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 20e2c583-059e-4143-b90d-4d1a6c4ed2bc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 974df618-fa82-42bd-9ad4-612f8f4a985c # Read
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a2302716-ea39-42e0-a7ec-1c3cd2214eac
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 88d092b2-6fa2-40df-aaf9-feccc0dc1a19
        userCondition: null
fields:
  0c515fa0-cbdd-4bd9-8267-917a447e5702: # User
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: user
    instructions: null
    name: User
    searchable: true
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      selectionLabel: null
      showSiteMenu: true
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Users
  3c50a00d-c61b-4018-bed4-f1685a215e01: # Comment
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: comment
    instructions: null
    name: Comment
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  974df618-fa82-42bd-9ad4-612f8f4a985c: # Read
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: read
    instructions: null
    name: Read
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  cea55199-bbc5-4529-8451-c12a00ff1080: # Date
    columnSuffix: null
    contentColumnType: datetime
    fieldGroup: null
    handle: date
    instructions: null
    name: Date
    searchable: true
    settings:
      max: null
      min: null
      minuteIncrement: 30
      showDate: true
      showTime: true
      showTimeZone: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Date
