changedFieldIndicator: null
field: 6e83784c-1c34-4973-9929-0307ffb6cff0 # Answers
fieldLayouts:
  f084b756-8fce-410b-898a-c6453ce96d15:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d9049b67-c562-4142-baad-49de0077690b # Answer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 75fb85b6-1d4f-4387-b5b4-946227102969
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a4e95883-3e35-47c5-bf4b-9d6357859fe8 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10faf9a0-52ae-45ba-b96b-1e2e463d0ef0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2e7aa32f-0920-4c19-973f-fd93c62c21d3 # Correct
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7622b53b-398e-44c5-b47c-434b3d370678
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: da10f3a1-aab6-47c4-8b15-edc3a7c6ed88
        userCondition: null
fields:
  2e7aa32f-0920-4c19-973f-fd93c62c21d3: # Correct
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: correct
    instructions: null
    name: Correct
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  a4e95883-3e35-47c5-bf4b-9d6357859fe8: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:f6dc0b30-2f16-4c2d-ad2e-849d3de5d0f9' # Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:a6dafdf7-e4c0-4943-aff3-e481bbdf23fc' # Evidence
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources:
        - 'volume:f6dc0b30-2f16-4c2d-ad2e-849d3de5d0f9' # Uploads
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  d9049b67-c562-4142-baad-49de0077690b: # Answer
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: answer
    instructions: null
    name: Answer
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
