contentColumnType: text
fieldGroup: 67ac5777-9885-4cde-bb93-527d48b311e0
handle: achievementLabel
instructions: 'Label for add button and title for the table.'
name: 'Achievement Label'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
