contentColumnType: string
fieldGroup: cce231c0-8af7-4fa9-8bba-17840a90fcc2
handle: attemptUnit
instructions: ''
name: 'Attempt Unit'
searchable: true
settings:
  limit: '1'
  localizeRelations: false
  selectionLabel: ''
  sources:
    - 'section:090b3c24-a9ac-4935-a919-c4fc8a3099b0'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
