contentColumnType: string
fieldGroup: cce231c0-8af7-4fa9-8bba-17840a90fcc2
handle: attemptAnswers
instructions: ''
name: 'Attempt Answers'
searchable: true
settings:
  contentTable: '`craft_matrixcontent_attemptanswers`'
  maxBlocks: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: none
type: craft\fields\Matrix
