columnSuffix: mckldiyg
contentColumnType: string
fieldGroup: 7f07c2bb-4fec-43ab-a281-bcb564148b2b # Users
handle: basePayments
instructions: null
name: 'Base Payments'
searchable: false
settings:
  contentTable: '{{%matrixcontent_basepayments}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
