columnSuffix: null
contentColumnType: string
fieldGroup: f4fdf728-2474-483c-8746-0b3bfcdb988a # Taskbooks
handle: companyTaskbooks
instructions: ''
name: 'Company Taskbooks'
searchable: false
settings:
  allowSelfRelations: false
  limit: ''
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: false
  source: null
  sources:
    - 'section:0db8b604-3d85-4638-bc64-f1d73e2e9aba' # Taskbooks
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
