contentColumnType: integer(10)
fieldGroup: f09af15b-015a-415a-b707-81fa9d1a1d69
handle: companyRemainingLicences
instructions: ''
name: 'Company Remaining Licences'
searchable: true
settings:
  decimals: '0'
  max: ''
  min: '0'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
