columnSuffix: null
contentColumnType: string
fieldGroup: 47ae7220-5336-4c43-9d2c-e7dedf6003df # Globals
handle: customFields
instructions: ''
name: 'Custom Fields'
searchable: true
settings:
  contentTable: '{{%matrixcontent_customfields}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
