columnSuffix: null
contentColumnType: boolean
fieldGroup: fe9133b9-1ac4-4551-9989-99fd7865a70c # Cycles
handle: cycleNotifyStart
instructions: null
name: 'Cycle Notify Start'
searchable: true
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
