columnSuffix: null
contentColumnType: text
fieldGroup: fe9133b9-1ac4-4551-9989-99fd7865a70c # Cycles
handle: cycleName
instructions: ''
name: 'Cycle Name'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
