columnSuffix: null
contentColumnType: string
fieldGroup: fe9133b9-1ac4-4551-9989-99fd7865a70c # Cycles
handle: cycleNotifyReminderFrequency
instructions: null
name: 'Cycle Notify Reminder Frequency'
searchable: true
settings:
  columnType: string
  options:
    -
      __assoc__:
        -
          - label
          - Weekly
        -
          - value
          - weekly
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Monthly
        -
          - value
          - monthly
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Quartley
        -
          - value
          - quartley
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Yearly
        -
          - value
          - yearly
        -
          - default
          - '1'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
