columnSuffix: null
contentColumnType: string
fieldGroup: fe9133b9-1ac4-4551-9989-99fd7865a70c # Cycles
handle: cycleDurationType
instructions: null
name: 'Cycle Duration Type'
searchable: true
settings:
  columnType: string
  options:
    -
      __assoc__:
        -
          - label
          - Year
        -
          - value
          - year
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Quarter
        -
          - value
          - quarter
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Month
        -
          - value
          - month
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Open
        -
          - value
          - open
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
