columnSuffix: null
contentColumnType: boolean
fieldGroup: f5eec841-a56b-474d-b01a-8ad8158d89b8 # Legacy
handle: dataImported
instructions: ''
name: 'Data Imported'
searchable: true
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
