contentColumnType: boolean
fieldGroup: f09af15b-015a-415a-b707-81fa9d1a1d69
handle: dataCleanManagersUserCompany
instructions: ''
name: 'Data Clean Managers User Company'
searchable: true
settings:
  default: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
