columnSuffix: krfnpvlj
contentColumnType: string
fieldGroup: f4fdf728-2474-483c-8746-0b3bfcdb988a # Taskbooks
handle: externalStatus
instructions: ''
name: 'External Status'
searchable: false
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - 'Not Selected'
        -
          - value
          - notSelected
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Selected
        -
          - value
          - selected
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Sampled
        -
          - value
          - sampled
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
