columnSuffix: null
contentColumnType: string
fieldGroup: f4fdf728-2474-483c-8746-0b3bfcdb988a # Taskbooks
handle: externalAssessor
instructions: ''
name: 'External Assessor'
searchable: false
settings:
  allowSelfRelations: false
  limit: '1'
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: null
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Users
