columnSuffix: null
contentColumnType: string
fieldGroup: 3f934bd7-b755-4330-88af-dd41d6ea990b # Theme
handle: homeSlider
instructions: null
name: 'Home Slider'
searchable: true
settings:
  contentTable: '{{%matrixcontent_homeslider}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
