contentColumnType: string
fieldGroup: 3f934bd7-b755-4330-88af-dd41d6ea990b
handle: homeSlider
instructions: ''
name: 'Home Slider'
searchable: true
settings:
  contentTable: '{{%matrixcontent_homeslider}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
