columnSuffix: hlmuhzgj
contentColumnType: boolean
fieldGroup: fa8667ae-97e6-4811-8904-29e4cfd55fdd # Skill Matrix
handle: isSkillsMatrix
instructions: null
name: 'Is Skills Matrix?'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
