contentColumnType: text
fieldGroup: f5eec841-a56b-474d-b01a-8ad8158d89b8
handle: legacyResultFiles
instructions: ''
name: 'Legacy Result Files'
searchable: true
settings:
  charLimit: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
