columnSuffix: null
contentColumnType: string
fieldGroup: f09af15b-015a-415a-b707-81fa9d1a1d69 # Structure
handle: locationCompany
instructions: ''
name: 'Location Company '
searchable: true
settings:
  allowSelfRelations: false
  limit: '1'
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: null
  sources:
    - 'section:86faf121-d218-4348-8ab8-de457b46aa63' # Companies
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
