contentColumnType: string
fieldGroup: 47ae7220-5336-4c43-9d2c-e7dedf6003df
handle: location
instructions: ''
name: Location
searchable: true
settings:
  googleApiKey: $GOOGLE_API_KEY
translationKeyFormat: null
translationMethod: none
type: nthmedia\entrygpscoordinates\fields\EntryCoordinates
