columnSuffix: null
contentColumnType: string
fieldGroup: 7f07c2bb-4fec-43ab-a281-bcb564148b2b # Users
handle: managerLevel
instructions: ''
name: 'Manager Level'
searchable: true
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - 'Level One'
        -
          - value
          - '1'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Level Two'
        -
          - value
          - '2'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Level Three'
        -
          - value
          - '3'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Level Four'
        -
          - value
          - '4'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
