contentColumnType: boolean
fieldGroup: 67ac5777-9885-4cde-bb93-527d48b311e0
handle: moduleGroupTaskbooks
instructions: 'Include this module group in taskbook options?'
name: Taskbooks
searchable: true
settings:
  default: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
