columnSuffix: null
contentColumnType: 'decimal(12,2)'
fieldGroup: f4fdf728-2474-483c-8746-0b3bfcdb988a # Taskbooks
handle: moduleSingleCost
instructions: 'Cost if purchased as individual optional module group.'
name: 'Module Group Single Cost'
searchable: true
settings:
  decimals: 2
  defaultValue: 0
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
