columnSuffix: null
contentColumnType: 'decimal(12,2)'
fieldGroup: f4fdf728-2474-483c-8746-0b3bfcdb988a # Taskbooks
handle: moduleMaxCost
instructions: ''
name: 'Module Group Max Cost'
searchable: true
settings:
  decimals: '2'
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: ''
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
