contentColumnType: boolean
fieldGroup: 67ac5777-9885-4cde-bb93-527d48b311e0
handle: moduleGroupAllCompanies
instructions: 'Select either All Companies or select Companies and results for modules in this group will be saved by the company rather than an individual user.  '
name: 'All Companies'
searchable: true
settings:
  default: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
