contentColumnType: text
fieldGroup: 67ac5777-9885-4cde-bb93-527d48b311e0
handle: moduleDescription
instructions: ''
name: 'Module Description'
searchable: true
settings:
  charLimit: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
