columnSuffix: null
contentColumnType: text
fieldGroup: f4fdf728-2474-483c-8746-0b3bfcdb988a # Taskbooks
handle: moduleCosts
instructions: ''
name: 'Module Group Costs'
searchable: true
settings:
  addRowLabel: 'Add a row'
  columnType: text
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - 'No. Optional Module Groups'
            -
              - handle
              - optionalModules
            -
              - width
              - ''
            -
              - type
              - number
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - Cost
            -
              - handle
              - cost
            -
              - width
              - ''
            -
              - type
              - number
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
        -
          - col2
          - ''
  maxRows: ''
  minRows: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
