contentColumnType: integer(10)
fieldGroup: 67ac5777-9885-4cde-bb93-527d48b311e0
handle: moduleCompletedValue
instructions: 'Enter the total value of the points needed to complete this module.'
name: 'Module Completed Value'
searchable: true
settings:
  decimals: '0'
  max: ''
  min: '0'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
