contentColumnType: text
fieldGroup: 67ac5777-9885-4cde-bb93-527d48b311e0
handle: moduleCosts
instructions: ''
name: 'Taskbook Module Costs'
searchable: true
settings:
  addRowLabel: 'Add a row'
  columnType: text
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - 'No. Optional Taskbook Groups'
            -
              - handle
              - optionalModules
            -
              - width
              - ''
            -
              - type
              - number
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - Cost
            -
              - handle
              - cost
            -
              - width
              - ''
            -
              - type
              - number
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
        -
          - col2
          - ''
  maxRows: ''
  minRows: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
