contentColumnType: integer(10)
fieldGroup: 67ac5777-9885-4cde-bb93-527d48b311e0
handle: moduleMinimumOptional
instructions: ''
name: 'Taskbook Module Minimum Optional'
searchable: true
settings:
  decimals: 0
  defaultValue: '0'
  max: null
  min: '0'
  prefix: ''
  size: null
  suffix: 'optional modules'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
