columnSuffix: null
contentColumnType: string
fieldGroup: f4fdf728-2474-483c-8746-0b3bfcdb988a # Taskbooks
handle: packageReviews
instructions: ''
name: 'Package Reviews'
searchable: true
settings:
  columns:
    __assoc__:
      -
        - eed6767c-11d8-46d2-b3d5-47ef288cd76b # Step ID
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 92d2e862-77f6-43f3-aa6e-cd75c38d424d # Step Name
        -
          __assoc__:
            -
              - width
              - ''
      -
        - e97c33b5-d88c-43c2-a829-e12ba86c75ac # Step Type
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 13071690-5bed-43f9-8afb-8c2c799eac7e # Review User
        -
          __assoc__:
            -
              - width
              - ''
      -
        - e927b48c-3108-4edd-a018-67e44c2989d5 # Review Date
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 7497821d-a351-4210-97ac-024153a093af # Review Passed
        -
          __assoc__:
            -
              - width
              - ''
      -
        - e98e5085-4cf9-46ca-818c-b71e74ed4eaa # Review Comment
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_packagereviews}}'
  fieldLayout: table
  maxRows: ''
  minRows: ''
  placeholderKey: null
  propagationMethod: all
  selectionLabel: ''
  staticField: ''
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
