contentColumnType: string
fieldGroup: f4fdf728-2474-483c-8746-0b3bfcdb988a
handle: packageJobRole
instructions: ''
name: 'Package Job Role'
searchable: true
settings:
  allowLimit: false
  allowMultipleSources: false
  branchLimit: ''
  limit: null
  localizeRelations: false
  selectionLabel: ''
  source: 'group:d83da856-af9d-458e-8b34-08ff74c012b5'
  sources: '*'
  targetSiteId: null
  validateRelatedElements: ''
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
