contentColumnType: string
fieldGroup: f4fdf728-2474-483c-8746-0b3bfcdb988a
handle: packageWorkflow
instructions: ''
name: 'Package Workflow'
searchable: true
settings:
  limit: '1'
  localizeRelations: false
  selectionLabel: ''
  source: null
  sources:
    - 'section:c0a51ffd-8054-40a9-824f-32657b83f14c'
  targetSiteId: null
  validateRelatedElements: ''
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
