columnSuffix: null
contentColumnType: string
fieldGroup: f4fdf728-2474-483c-8746-0b3bfcdb988a # Taskbooks
handle: packageModuleGroups
instructions: ''
name: 'Package Module Groups'
searchable: true
settings:
  columns:
    __assoc__:
      -
        - 00afc899-b37a-415c-8829-b06a42a8638f # Module Group
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 8b738285-1f1f-4f66-bb77-bdf61a7f234e # Mandatory
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 9a61af4b-dccb-4d5e-9bc1-53b775f9de18 # Level
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 7209f99b-e88b-403f-b8ba-fbb0301b5c0f # Paid
        -
          __assoc__:
            -
              - width
              - ''
      -
        - cad6f0cc-99c2-432e-b299-3990a84d96fc # Cost
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_packagemodulegroups}}'
  fieldLayout: table
  maxRows: ''
  minRows: ''
  placeholderKey: null
  propagationMethod: all
  selectionLabel: ''
  staticField: ''
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
