columnSuffix: null
contentColumnType: string
fieldGroup: f4fdf728-2474-483c-8746-0b3bfcdb988a # Taskbooks
handle: packageStatus
instructions: null
name: 'Package Status'
searchable: true
settings:
  columnType: string
  options:
    -
      __assoc__:
        -
          - label
          - Active
        -
          - value
          - active
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Locked
        -
          - value
          - locked
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Complete
        -
          - value
          - complete
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Failed
        -
          - value
          - failed
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
