contentColumnType: boolean
fieldGroup: f4fdf728-2474-483c-8746-0b3bfcdb988a
handle: packageRevision
instructions: ''
name: 'Package Revision'
searchable: true
settings:
  default: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
