contentColumnType: text
fieldGroup: f4fdf728-2474-483c-8746-0b3bfcdb988a
handle: packageLog
instructions: ''
name: 'Package Log'
searchable: true
settings:
  addRowLabel: 'Add a row'
  columnType: text
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Date
            -
              - handle
              - date
            -
              - width
              - ''
            -
              - type
              - date
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - 'User Message'
            -
              - handle
              - userMessage
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col3
        -
          __assoc__:
            -
              - heading
              - 'Admin Message'
            -
              - handle
              - adminMessage
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col4
        -
          __assoc__:
            -
              - heading
              - 'User ID'
            -
              - handle
              - userId
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col5
        -
          __assoc__:
            -
              - heading
              - 'User Full Name'
            -
              - handle
              - userFullname
            -
              - width
              - ''
            -
              - type
              - singleline
  defaults:
    -
      __assoc__:
        1:
          - col2
          - ''
        2:
          - col3
          - ''
        3:
          - col4
          - ''
        4:
          - col5
          - ''
  maxRows: ''
  minRows: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
