contentColumnType: string
fieldGroup: 0d277023-1a22-42a9-9b23-8d89a23cc677
handle: pageContent
instructions: ''
name: Content
searchable: true
settings:
  contentTable: '{{%matrixcontent_pagecontent}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
