columnSuffix: null
contentColumnType: text
fieldGroup: 0d277023-1a22-42a9-9b23-8d89a23cc677 # Pages
handle: pageHeading
instructions: ''
name: Heading
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
