columnSuffix: null
contentColumnType: string
fieldGroup: 7ac02e26-c0e2-4b21-b756-bfe7243fa353 # Products
handle: productType
instructions: ''
name: 'Product Type'
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: ''
  limit: null
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: false
  source: 'group:7b89d06c-f8a7-409a-8e43-562476090b7f' # Product Types
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
