columnSuffix: ebrsugdt
contentColumnType: string
fieldGroup: 7ac02e26-c0e2-4b21-b756-bfe7243fa353 # Products
handle: productManufacturerEmail
instructions: ''
name: 'Product Manufacturer Email'
searchable: false
settings:
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
