contentColumnType: string
fieldGroup: 169df08f-5dca-4d57-8005-9e0226ec5dcc
handle: reportRecipients
instructions: ''
name: 'Report Recipients'
searchable: true
settings:
  limit: ''
  localizeRelations: false
  selectionLabel: ''
  sources: 'group:2group:1group:3'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Users
