contentColumnType: integer(10)
fieldGroup: 169df08f-5dca-4d57-8005-9e0226ec5dcc
handle: reportDays
instructions: ''
name: 'Report Days'
searchable: true
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: '0'
  prefix: ''
  size: null
  suffix: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
