contentColumnType: string
fieldGroup: 169df08f-5dca-4d57-8005-9e0226ec5dcc
handle: reportUnits
instructions: ''
name: 'Report Units'
searchable: true
settings:
  limit: ''
  localizeRelations: false
  selectionLabel: ''
  sources: 'section:7'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
