contentColumnType: datetime
fieldGroup: 169df08f-5dca-4d57-8005-9e0226ec5dcc
handle: reportLastSentDate
instructions: ''
name: 'Report Last Sent Date'
searchable: true
settings:
  minuteIncrement: '30'
  showDate: 1
  showTime: 0
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
