contentColumnType: text
fieldGroup: 169df08f-5dca-4d57-8005-9e0226ec5dcc
handle: reportEmails
instructions: ''
name: 'Report Emails'
searchable: true
settings:
  charLimit: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
