contentColumnType: string
fieldGroup: 169df08f-5dca-4d57-8005-9e0226ec5dcc
handle: reportModules
instructions: ''
name: 'Report Modules'
searchable: true
settings:
  limit: ''
  localizeRelations: false
  selectionLabel: ''
  sources: 'section:6'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
