columnSuffix: null
contentColumnType: string
fieldGroup: 169df08f-5dca-4d57-8005-9e0226ec5dcc # Reports
handle: reportResultStandardType
instructions: ''
name: 'Report Results Standard Type'
searchable: true
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - Endorsed
        -
          - value
          - endorsed
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Expiring
        -
          - value
          - expiring
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
