contentColumnType: boolean
fieldGroup: 169df08f-5dca-4d57-8005-9e0226ec5dcc
handle: reportNoDates
instructions: ''
name: 'Report No Dates'
searchable: true
settings:
  default: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
