contentColumnType: integer(10)
fieldGroup: 169df08f-5dca-4d57-8005-9e0226ec5dcc
handle: reportCount
instructions: ''
name: 'Report Count'
searchable: true
settings:
  decimals: '0'
  max: ''
  min: '0'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
