contentColumnType: string
fieldGroup: 24e619f3-3a4b-47a9-beea-4dc60343c548
handle: resultEndorsedUser
instructions: ''
name: 'Result Endorsed User'
searchable: true
settings:
  limit: '1'
  localizeRelations: false
  selectionLabel: ''
  sources: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Users
