contentColumnType: boolean
fieldGroup: 67ac5777-9885-4cde-bb93-527d48b311e0
handle: resultDisplayValue
instructions: ''
name: 'Result Display Value'
searchable: true
settings:
  default: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
