columnSuffix: null
contentColumnType: string
fieldGroup: 24e619f3-3a4b-47a9-beea-4dc60343c548 # Results
handle: resultPackage
instructions: 'If taskbook > unitResultRollover is off, unit results are locked to package.'
name: 'Result Package'
searchable: false
settings:
  allowSelfRelations: false
  limit: ''
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: false
  source: null
  sources:
    - 'section:0c63d248-a060-4ecd-b881-00607c9f4024' # Taskbook Packages
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
