columnSuffix: null
contentColumnType: string
fieldGroup: 7ac02e26-c0e2-4b21-b756-bfe7243fa353 # Products
handle: resultProduct
instructions: ''
name: 'Result Product'
searchable: false
settings:
  allowSelfRelations: false
  limit: ''
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: false
  source: null
  sources:
    - 'section:3d20ce59-1bf4-4cb2-a4b9-1c04d290e5ad' # Products
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
