columnSuffix: null
contentColumnType: string
fieldGroup: 24e619f3-3a4b-47a9-beea-4dc60343c548 # Results
handle: resultAttempts
instructions: null
name: 'Result Attempts'
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: true
  sources:
    - 'section:51a18e4b-1a36-4210-8769-a5b8f28f3a5f' # Attempts
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
