columnSuffix: xbpgidpg
contentColumnType: boolean
fieldGroup: 24e619f3-3a4b-47a9-beea-4dc60343c548 # Results
handle: resultOutcome
instructions: null
name: 'Result Outcome'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
