contentColumnType: boolean
fieldGroup: 67ac5777-9885-4cde-bb93-527d48b311e0
handle: resultDisplayFinishDate
instructions: ''
name: 'Result Display Finish Date'
searchable: true
settings:
  default: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
