columnSuffix: null
contentColumnType: text
fieldGroup: 24e619f3-3a4b-47a9-beea-4dc60343c548 # Results
handle: resultLocation
instructions: null
name: 'Result Location'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
