columnSuffix: null
contentColumnType: text
fieldGroup: 24e619f3-3a4b-47a9-beea-4dc60343c548 # Results
handle: resultComponentResults
instructions: null
name: 'Result Component Results'
searchable: true
settings:
  addRowLabel: 'Add a row'
  columnType: text
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - ID
            -
              - handle
              - id
            -
              - width
              - ''
            -
              - type
              - number
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - Title
            -
              - handle
              - title
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col3
        -
          __assoc__:
            -
              - heading
              - 'Target Hours'
            -
              - handle
              - targetHours
            -
              - width
              - ''
            -
              - type
              - number
      -
        - col4
        -
          __assoc__:
            -
              - heading
              - 'Target Points'
            -
              - handle
              - targetPoints
            -
              - width
              - ''
            -
              - type
              - number
      -
        - col5
        -
          __assoc__:
            -
              - heading
              - 'Endorsed Hours'
            -
              - handle
              - endorsedHours
            -
              - width
              - ''
            -
              - type
              - number
      -
        - col6
        -
          __assoc__:
            -
              - heading
              - 'Endorsed Points'
            -
              - handle
              - endorsedPoints
            -
              - width
              - ''
            -
              - type
              - number
      -
        - col7
        -
          __assoc__:
            -
              - heading
              - Complete
            -
              - handle
              - complete
            -
              - width
              - ''
            -
              - type
              - lightswitch
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
