columnSuffix: null
contentColumnType: string
fieldGroup: 24e619f3-3a4b-47a9-beea-4dc60343c548 # Results
handle: resultCompany
instructions: null
name: 'Result Company'
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  selectionLabel: null
  showSiteMenu: true
  sources:
    - 'section:86faf121-d218-4348-8ab8-de457b46aa63' # Companies
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
