contentColumnType: string
fieldGroup: 24e619f3-3a4b-47a9-beea-4dc60343c548
handle: resultAttempts
instructions: ''
name: 'Result Attempts'
searchable: true
settings:
  limit: ''
  localizeRelations: false
  selectionLabel: ''
  sources:
    - 'section:51a18e4b-1a36-4210-8769-a5b8f28f3a5f' # Attempts
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
