columnSuffix: null
contentColumnType: string
fieldGroup: 24e619f3-3a4b-47a9-beea-4dc60343c548 # Results
handle: resultStatus
instructions: ''
name: 'Result Status'
searchable: true
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - Draft
        -
          - value
          - draft
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Revision
        -
          - value
          - revision
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Pending
        -
          - value
          - pending
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Endorsed
        -
          - value
          - endorsed
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Failed
        -
          - value
          - failed
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Blocked
        -
          - value
          - blocked
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Active
        -
          - value
          - active
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Complete
        -
          - value
          - complete
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Incomplete
        -
          - value
          - incomplete
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
