contentColumnType: string
fieldGroup: 24e619f3-3a4b-47a9-beea-4dc60343c548
handle: resultEvidence
instructions: ''
name: 'Result Evidence'
searchable: true
settings:
  allowedKinds:
    - image
    - pdf
  defaultUploadLocationSource: 'volume:a6dafdf7-e4c0-4943-aff3-e481bbdf23fc'
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  restrictFiles: ''
  selectionLabel: ''
  singleUploadLocationSource: 'volume:a6dafdf7-e4c0-4943-aff3-e481bbdf23fc'
  singleUploadLocationSubpath: '{author.id}'
  sources: '*'
  useSingleFolder: '1'
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
