columnSuffix: null
contentColumnType: boolean
fieldGroup: 67ac5777-9885-4cde-bb93-527d48b311e0 # Modules
handle: resultDisplayType
instructions: ''
name: 'Result Display Type'
searchable: true
settings:
  default: true
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
