contentColumnType: integer(10)
fieldGroup: 24e619f3-3a4b-47a9-beea-4dc60343c548
handle: resultScore
instructions: ''
name: 'Result Score'
searchable: true
settings:
  decimals: '0'
  max: ''
  min: '0'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
