columnSuffix: null
contentColumnType: string
fieldGroup: fa8667ae-97e6-4811-8904-29e4cfd55fdd # Skill Matrix
handle: skillLevel
instructions: null
name: 'Skill Level'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: 1
  localizeRelations: false
  maintainHierarchy: true
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  source: 'group:24f73b0f-4768-4a11-a61c-52cabf296f38' # Skill Levels
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
