columnSuffix: null
contentColumnType: string
fieldGroup: 67ac5777-9885-4cde-bb93-527d48b311e0 # Modules
handle: skillsMatrixLevels
instructions: ''
name: 'Skills Matrix Levels'
searchable: false
settings:
  contentTable: '{{%matrixcontent_skillsmatrixlevels}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
