columnSuffix: zkplxfnd
contentColumnType: text
fieldGroup: 24e619f3-3a4b-47a9-beea-4dc60343c548 # Results
handle: skillMatrixLevel
instructions: ''
name: 'Skill Matrix Level'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
