columnSuffix: winjxerx
contentColumnType: 'decimal(11,1)'
fieldGroup: fa8667ae-97e6-4811-8904-29e4cfd55fdd # Skill Matrix
handle: skillLevelNumber
instructions: ''
name: 'Skill Level Number'
searchable: false
settings:
  decimals: '1'
  defaultValue: null
  max: null
  min: '0.0'
  prefix: null
  previewCurrency: ''
  previewFormat: decimal
  size: '1'
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
