columnSuffix: null
contentColumnType: integer(10)
fieldGroup: fe9133b9-1ac4-4551-9989-99fd7865a70c # Cycles
handle: targetPoints
instructions: null
name: 'Target Points'
searchable: true
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
