columnSuffix: null
contentColumnType: string
fieldGroup: fe9133b9-1ac4-4551-9989-99fd7865a70c # Cycles
handle: targetType
instructions: 'Select when the module will be completed.'
name: 'Target Type'
searchable: true
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - Points
        -
          - value
          - points
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Hours
        -
          - value
          - hours
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Points AND Hours'
        -
          - value
          - pointsAndHours
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Points OR Hours'
        -
          - value
          - pointsOrHours
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
