contentColumnType: string
fieldGroup: f4fdf728-2474-483c-8746-0b3bfcdb988a
handle: taskbookGroupModules
instructions: ''
name: 'Taskbook Group Modules'
searchable: true
settings:
  limit: null
  localizeRelations: false
  readOnly: ''
  selectionLabel: ''
  source: null
  sources:
    - 'section:e9e30b72-2c16-4035-b4b9-e1e4c42ebb3a'
  targetFieldId: null
  targetSiteId: null
  validateRelatedElements: ''
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: robuust\reverserelations\fields\ReverseEntries
