contentColumnType: string
fieldGroup: 67ac5777-9885-4cde-bb93-527d48b311e0
handle: taskbookGroup
instructions: ''
name: 'Taskbook Group'
searchable: true
settings:
  allowLimit: false
  allowMultipleSources: false
  branchLimit: ''
  limit: null
  localizeRelations: false
  selectionLabel: ''
  source: 'group:a8731481-f6d5-4f6e-9d29-0bd442774b61'
  sources: '*'
  targetSiteId: null
  validateRelatedElements: ''
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
