columnSuffix: null
contentColumnType: string
fieldGroup: f4fdf728-2474-483c-8746-0b3bfcdb988a # Taskbooks
handle: taskbookFiles
instructions: ''
name: 'Taskbook Files'
searchable: true
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:f6dc0b30-2f16-4c2d-ad2e-849d3de5d0f9' # Uploads
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:a6dafdf7-e4c0-4943-aff3-e481bbdf23fc' # Evidence
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:f6dc0b30-2f16-4c2d-ad2e-849d3de5d0f9' # Uploads
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
