contentColumnType: string
fieldGroup: f09af15b-015a-415a-b707-81fa9d1a1d69
handle: teamSecondaryManagers
instructions: ''
name: 'Team Secondary Managers'
searchable: true
settings:
  limit: ''
  localizeRelations: false
  selectionLabel: ''
  sources:
    - 'group:7765376d-5d95-4bb2-ad49-e9dbcd7acf4a'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Users
