contentColumnType: text
fieldGroup: f09af15b-015a-415a-b707-81fa9d1a1d69
handle: teamName
instructions: ''
name: 'Team Name'
searchable: true
settings:
  charLimit: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
