contentColumnType: integer(10)
fieldGroup: cce231c0-8af7-4fa9-8bba-17840a90fcc2
handle: testMaxAttempts
instructions: ''
name: 'Max Attempts'
searchable: true
settings:
  decimals: '0'
  max: ''
  min: '0'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
