contentColumnType: string
fieldGroup: cce231c0-8af7-4fa9-8bba-17840a90fcc2
handle: testQuestions
instructions: ''
name: 'Test Questions'
searchable: true
settings:
  contentTable: '`craft_matrixcontent_testquestions`'
  maxBlocks: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: none
type: craft\fields\Matrix
