contentColumnType: smallint(3)
fieldGroup: cce231c0-8af7-4fa9-8bba-17840a90fcc2
handle: testPassPercent
instructions: ''
name: 'Test Pass Percent'
searchable: true
settings:
  decimals: '0'
  max: '100'
  min: '0'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
