columnSuffix: null
contentColumnType: smallint(3)
fieldGroup: cce231c0-8af7-4fa9-8bba-17840a90fcc2 # Tests
handle: testPassPercent
instructions: null
name: 'Test Pass Percent'
searchable: true
settings:
  decimals: 0
  defaultValue: null
  max: 100
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
