columnSuffix: null
contentColumnType: text
fieldGroup: 67ac5777-9885-4cde-bb93-527d48b311e0 # Modules
handle: unitIntro
instructions: null
name: 'Unit Intro'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes:
    - f6dc0b30-2f16-4c2d-ad2e-849d3de5d0f9 # Uploads
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: null
  purifyHtml: true
  redactorConfig: null
  removeEmptyTags: true
  removeInlineStyles: true
  removeNbsp: true
  showHtmlButtonForNonAdmins: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
