columnSuffix: null
contentColumnType: string
fieldGroup: 67ac5777-9885-4cde-bb93-527d48b311e0 # Modules
handle: unitImage
instructions: ''
name: 'Unit Image'
searchable: true
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:f6dc0b30-2f16-4c2d-ad2e-849d3de5d0f9' # Uploads
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Add a unit image'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  singleUploadLocationSource: 'volume:a6dafdf7-e4c0-4943-aff3-e481bbdf23fc' # Evidence
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:f6dc0b30-2f16-4c2d-ad2e-849d3de5d0f9' # Uploads
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
