columnSuffix: null
contentColumnType: string
fieldGroup: 67ac5777-9885-4cde-bb93-527d48b311e0 # Modules
handle: unitImage
instructions: null
name: 'Unit Image'
searchable: true
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultUploadLocationSource: 'volume:f6dc0b30-2f16-4c2d-ad2e-849d3de5d0f9' # Uploads
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:a6dafdf7-e4c0-4943-aff3-e481bbdf23fc' # Evidence
  restrictedLocationSubpath: null
  selectionLabel: 'Add a unit image'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  sources:
    - 'volume:f6dc0b30-2f16-4c2d-ad2e-849d3de5d0f9' # Uploads
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
