columnSuffix: null
contentColumnType: string
fieldGroup: 67ac5777-9885-4cde-bb93-527d48b311e0 # Modules
handle: unitType
instructions: ''
name: 'Unit Type'
searchable: true
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - Evidence
        -
          - value
          - evidence
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - E-Learning
        -
          - value
          - elearning
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
