contentColumnType: text
fieldGroup: 7f07c2bb-4fec-43ab-a281-bcb564148b2b
handle: userSearch
instructions: ''
name: 'User Search'
searchable: true
settings:
  allowSelect: ''
  columnType: text
  decimals: '0'
  fieldTwig: '{{ user.userTeam.first.title|raw  }} {{ user.userTeam.first.teamCompany.first.title|raw }}'
  parseBeforeSave: ''
  parseOnMove: ''
  showField: ''
translationKeyFormat: null
translationMethod: none
type: aelvan\preparsefield\fields\PreparseFieldType
