contentColumnType: text
fieldGroup: 7f07c2bb-4fec-43ab-a281-bcb564148b2b
handle: userLicenceSource
instructions: ''
name: 'User Licence Source'
searchable: true
settings:
  charLimit: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
