contentColumnType: string
fieldGroup: 7f07c2bb-4fec-43ab-a281-bcb564148b2b
handle: userTeam
instructions: ''
name: 'User Team'
searchable: true
settings:
  limit: '1'
  localizeRelations: false
  selectionLabel: ''
  sources:
    - 'section:bcf0ea1d-9495-423e-ac83-ef089790460c' # Teams
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
