contentColumnType: string
fieldGroup: 7f07c2bb-4fec-43ab-a281-bcb564148b2b
handle: userPayments
instructions: ''
name: 'User Payments'
searchable: true
settings:
  contentTable: '`craft_matrixcontent_userpayments`'
  maxBlocks: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: none
type: craft\fields\Matrix
