columnSuffix: null
contentColumnType: string
fieldGroup: 7f07c2bb-4fec-43ab-a281-bcb564148b2b # Users
handle: userLinkedUser
instructions: ''
name: 'User Linked User'
searchable: false
settings:
  allowSelfRelations: false
  limit: ''
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: null
  sources:
    - 'group:ab9197b3-7032-4015-ba4e-4939118952dd' # Users
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Users
