columnSuffix: null
contentColumnType: string
fieldGroup: 7f07c2bb-4fec-43ab-a281-bcb564148b2b # Users
handle: userTaskbooks
instructions: 'Select the taskbooks this user is able to review (if they have a reviewer job role).'
name: 'User Taskbooks'
searchable: false
settings:
  allowSelfRelations: false
  limit: ''
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: null
  sources:
    - 'section:0db8b604-3d85-4638-bc64-f1d73e2e9aba' # Taskbooks
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
