columnSuffix: null
contentColumnType: datetime
fieldGroup: 7f07c2bb-4fec-43ab-a281-bcb564148b2b # Users
handle: userStartDate
instructions: null
name: 'User Start Date'
searchable: true
settings:
  max: null
  min: null
  minuteIncrement: 30
  showDate: true
  showTime: false
  showTimeZone: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
