contentColumnType: text
fieldGroup: 7f07c2bb-4fec-43ab-a281-bcb564148b2b
handle: userCompanyName
instructions: ''
name: 'User Company Name'
searchable: true
settings:
  allowSelect: ''
  columnType: text
  decimals: '0'
  fieldTwig: '{{ user.userCompany | length ? user.userCompany.first().title }}'
  parseBeforeSave: ''
  parseOnMove: ''
  showField: '1'
translationKeyFormat: null
translationMethod: none
type: aelvan\preparsefield\fields\PreparseFieldType
