contentColumnType: datetime
fieldGroup: 7f07c2bb-4fec-43ab-a281-bcb564148b2b
handle: userExpiryDate
instructions: ''
name: 'User Expiry Date'
searchable: true
settings:
  minuteIncrement: '30'
  showDate: 1
  showTime: 0
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
