columnSuffix: null
contentColumnType: string
fieldGroup: 7f07c2bb-4fec-43ab-a281-bcb564148b2b # Users
handle: userCustomFields
instructions: ''
name: 'User Custom Fields'
searchable: true
settings:
  contentTable: '`craft_matrixcontent_usercustomfields`'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
