contentColumnType: string
fieldGroup: 7f07c2bb-4fec-43ab-a281-bcb564148b2b
handle: userReviewCompanies
instructions: 'User will be allowed to review for the selected companies.'
name: 'User Review Companies'
searchable: true
settings:
  limit: ''
  localizeRelations: false
  selectionLabel: ''
  source: null
  sources:
    - 'section:86faf121-d218-4348-8ab8-de457b46aa63'
  targetSiteId: null
  validateRelatedElements: ''
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
