columnSuffix: null
contentColumnType: text
fieldGroup: 7f07c2bb-4fec-43ab-a281-bcb564148b2b # Users
handle: userAddress
instructions: ''
name: 'User Address'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: '2'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
