columnSuffix: null
contentColumnType: string
fieldGroup: 7f07c2bb-4fec-43ab-a281-bcb564148b2b # Users
handle: userActiveUser
instructions: ''
name: 'User Active User'
searchable: false
settings:
  allowSelfRelations: false
  limit: ''
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: null
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Users
