enableVersioning: false
entryTypes:
  6aaa6123-97b5-479c-8de3-488d8813933e:
    fieldLayouts:
      70848f31-dc12-428f-873c-12acd93bbd10:
        tabs:
          -
            fields:
              1a8a5dc7-66a0-4520-957d-7dec3aa3cf2f:
                required: false
                sortOrder: 4
              1a27fa24-b0d3-491d-8b77-f1656c3afc77:
                required: false
                sortOrder: 2
              bebe1bc3-81ca-46c1-86ac-1ad88d0a0f92:
                required: false
                sortOrder: 3
              d1300c08-840a-419d-b910-de865842ddd8:
                required: false
                sortOrder: 1
              f6e76a64-5565-406e-8679-27b8adea6736:
                required: false
                sortOrder: 5
            name: Reports
            sortOrder: 1
          -
            fields:
              2f940be6-d44c-47bf-95b6-392608ee2547:
                required: false
                sortOrder: 7
              4e26dbf7-5c26-4bdd-abaf-efcd389366bc:
                required: false
                sortOrder: 10
              6fae9879-b107-4f41-9bc0-0f119a358ef1:
                required: false
                sortOrder: 9
              7b7af1dc-c01f-4f73-b3f4-a83ff572e941:
                required: false
                sortOrder: 6
              19bb4e6d-2834-456c-93b9-6b942b47b8d4:
                required: false
                sortOrder: 17
              27e57a2d-2938-41e8-ab58-72f377ca20c1:
                required: false
                sortOrder: 8
              8200bbc7-18f0-49da-a017-2fb3a82ee950:
                required: false
                sortOrder: 15
              a1b63d62-c6f0-443b-910f-1d6691b0e4a4:
                required: false
                sortOrder: 11
              ab55340f-38e6-4d9f-82eb-f3785c6c6ff8:
                required: false
                sortOrder: 4
              abb92e86-cb1b-456e-a618-befafa8e8a28:
                required: false
                sortOrder: 5
              c2e23d12-1d3f-4cbd-a3cb-be22ea64bdca:
                required: false
                sortOrder: 13
              c9d661c9-fd44-473b-a7ef-70f4bc6340ea:
                required: false
                sortOrder: 14
              d4ac5d73-4f3c-467c-a3c4-492a2205f858:
                required: false
                sortOrder: 18
              d500f1e4-fb5b-435a-af01-cc2402b4a8c3:
                required: false
                sortOrder: 3
              d4776dfe-b66f-4a88-931c-d2bebb2d68d1:
                required: false
                sortOrder: 2
              dd61054f-d009-4e76-9315-7bf23e0cbc22:
                required: false
                sortOrder: 1
              e05af851-b6aa-4f59-a43b-0ac897b54887:
                required: false
                sortOrder: 12
              f56275dc-26a8-46e7-bfb5-061917775684:
                required: false
                sortOrder: 16
            name: Criteria
            sortOrder: 2
          -
            fields:
              84ec75d0-1dcf-408a-bce8-4ea7b5370c3b:
                required: false
                sortOrder: 2
              c996fdb5-0318-4df3-87bd-b42b45db2cab:
                required: false
                sortOrder: 4
              dbedebea-c884-4f61-8f0f-ebc64b3a5ed2:
                required: false
                sortOrder: 3
              e0c4c343-2eda-4447-baf6-836f09723985:
                required: false
                sortOrder: 1
            name: Recipients
            sortOrder: 3
          -
            fields:
              c0866ad5-ca17-43d8-8a57-52ea3e84bbe2:
                required: false
                sortOrder: 1
            name: Data
            sortOrder: 4
    handle: reports
    hasTitleField: true
    name: Reports
    sortOrder: 1
    titleFormat: ''
    titleLabel: Title
handle: reports
name: Reports
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  47b102e1-4aed-4206-8420-dfd6e6684f7c:
    enabledByDefault: true
    hasUrls: true
    template: reporting/custom/_entry
    uriFormat: 'reporting/custom/{id}'
type: channel
