defaultPlacement: end
enableVersioning: true
handle: taskbooks
name: Taskbooks
propagationMethod: all
siteSettings:
  47b102e1-4aed-4206-8420-dfd6e6684f7c: # Skills Plus (en-GB)
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: c9778959-87e1-46ec-aad7-7605164a9bb9
type: structure
