defaultPlacement: end
enableVersioning: true
handle: taskbooks
name: Taskbooks
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  47b102e1-4aed-4206-8420-dfd6e6684f7c: # Skills Plus (en-GB)
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: taskbooks
type: channel
