defaultPlacement: end
enableVersioning: false
handle: units
name: Units
propagationMethod: all
siteSettings:
  47b102e1-4aed-4206-8420-dfd6e6684f7c: # Skills Plus (en-GB)
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: 921ca6e2-b29c-4578-9864-c560018b280c
type: structure
