enableVersioning: false
entryTypes:
  6bbfb167-5ead-4bd3-971d-7f756a5b4c8b:
    fieldLayouts:
      3d94edeb-73ba-41ad-b224-c77a85c59742:
        tabs:
          -
            fields:
              1d522b30-9aa0-4fc8-afd1-84e738233479:
                required: false
                sortOrder: 10
              1e5a2205-0d2d-4f4c-b087-a5f706ac0449:
                required: false
                sortOrder: 8
              4bb00585-cc77-465a-add8-7acdffe931ce:
                required: false
                sortOrder: 7
              28e570b6-14a0-4b5e-be07-37e03f6b9b8f:
                required: false
                sortOrder: 9
              98e01bd1-bcac-4523-8399-0c55010d13b6:
                required: false
                sortOrder: 2
              995ba33c-928b-43a5-8d39-53c4c36782ed:
                required: false
                sortOrder: 3
              6616a98b-5530-40e0-93db-6e73e439e274:
                required: false
                sortOrder: 6
              c708fb49-2ead-4372-bb3f-c925d3ab9f41:
                required: false
                sortOrder: 4
              d09c7ee9-90ad-4c7e-a8ec-a84e5f3457f0:
                required: false
                sortOrder: 5
              f2ab3047-5922-481b-a6bc-d1ced215dc10:
                required: false
                sortOrder: 1
            name: Unit
            sortOrder: 1
          -
            fields:
              8a7a272d-f35d-4ec6-9c9a-571c7f0f40d7:
                required: false
                sortOrder: 1
              4209884c-57c0-48b6-bb15-06361f5e0182:
                required: false
                sortOrder: 2
              e875ae7a-06f3-4063-a7c9-0b3fbb8f75b9:
                required: false
                sortOrder: 3
            name: Test
            sortOrder: 2
          -
            fields:
              22f6cba0-1e8a-4d82-8678-9a33b1d06163:
                required: false
                sortOrder: 2
              556fe388-9b99-4cda-835a-bc491fa00273:
                required: false
                sortOrder: 1
            name: Reccuring
            sortOrder: 3
          -
            fields:
              dc88c84b-17f2-4b8b-8cc6-124b5115c9cc:
                required: false
                sortOrder: 1
            name: Legacy
            sortOrder: 4
    handle: unit
    hasTitleField: true
    name: Unit
    sortOrder: 1
    titleFormat: ''
    titleLabel: Title
handle: units
name: Units
previewTargets: null
propagationMethod: all
siteSettings:
  47b102e1-4aed-4206-8420-dfd6e6684f7c:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
