dateModified: 1626704301
meta:
  __names__:
    0c63d248-a060-4ecd-b881-00607c9f4024: 'Taskbook Packages' # Taskbook Packages
    f1be4708-798f-4906-84b1-b8c6e54a32e3: Package # Package
plugins:
  dashboard-begone:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  entry-gps-coordinates:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  incognito-field:
    edition: standard
    enabled: true
    schemaVersion: 1.1.1
  preparse-field:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.5
    settings: null
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  reverserelations:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  sp:
    edition: standard
    enabled: true
    schemaVersion: 0.0.1
  super-table:
    enabled: '1'
    licenseKey: null
    schemaVersion: 2.2.1
    settings: null
  wordsmith:
    edition: standard
    enabled: true
    schemaVersion: 0.0.0.0
system:
  edition: pro
  live: true
  name: 'Skills Plus'
  schemaVersion: 3.4.10
  timeZone: UTC
