dateModified: 1628782249
graphql:
  publicToken:
    enabled: false
    expiryDate: null
meta:
  __names__:
    0b770895-5b1b-4424-976b-53d7cfd96fbe: Taskbook # Taskbook
    0c63d248-a060-4ecd-b881-00607c9f4024: 'Taskbook Packages' # Taskbook Packages
    0db8b604-3d85-4638-bc64-f1d73e2e9aba: Taskbooks # Taskbooks
    0ff8d9a2-50f8-473e-93c9-5eb5d41750f6: 'Company Managers' # Company Managers
    1d590683-b16e-4955-be62-315accb3e628: Reports # Reports
    2a75e796-1574-407e-8869-545d14d6d126: 'Scheme Managers' # Scheme Managers
    2fbdc981-206f-44f9-9f39-fdb605cff8f2: Company # Company
    3bf342f8-6a3e-465e-b665-d25d1860be54: 'Unit Result' # Unit Result
    6aaa6123-97b5-479c-8de3-488d8813933e: Reports # Reports
    6bbfb167-5ead-4bd3-971d-7f756a5b4c8b: Unit # Unit
    006ef470-d860-40ff-a431-e2515805f2e8: Pages # Pages
    7f4bb404-6c1a-4ec5-a311-25f912ea733a: 'HTML Content' # HTML Content
    8c1af673-0f01-4434-a6f0-86f01675d799: Pages # Pages
    9e4f32de-898b-4f03-b31a-af2c18541d54: Dashboard # Dashboard
    39d4cfb6-0d4f-496d-82ca-64d29f904a62: Attempt # Attempt
    51a18e4b-1a36-4210-8769-a5b8f28f3a5f: Attempts # Attempts
    78c5a5fd-a2f0-4482-a20c-fde7866eb5c0: Package # Package
    86faf121-d218-4348-8ab8-de457b46aa63: Companies # Companies
    090b3c24-a9ac-4935-a919-c4fc8a3099b0: Units # Units
    7765376d-5d95-4bb2-ad49-e9dbcd7acf4a: 'Team Managers' # Team Managers
    a1969b12-a29f-4cbc-ad95-96798d730775: Theme # Theme
    a6165775-faf3-4cc0-b6d6-069095d3ca39: CPD # CPD
    aa0a1650-9855-4bd3-a399-b549a74c19be: Taskbooks # Taskbooks
    ab9197b3-7032-4015-ba4e-4939118952dd: Users # Users
    abaff843-e57c-4cfa-bab2-3f4927f556d3: 'Module Result' # Module Result
    bcf0ea1d-9495-423e-ac83-ef089790460c: Teams # Teams
    c0a51ffd-8054-40a9-824f-32657b83f14c: 'Taskbook Workflows' # Taskbook Workflows
    c0345752-9e56-4de1-a2d2-da641c3708e0: Results # Results
    d87a0468-94af-4371-a7d8-59f8f3664b84: Dashboard # Dashboard
    d1813da3-56a4-441b-84ad-2a2bc2a9ab36: Workflow # Workflow
    dbd7f9dd-1424-48cc-8aba-f0533bce83be: Qualification # Qualification
    e9e30b72-2c16-4035-b4b9-e1e4c42ebb3a: Modules # Modules
    e34f85df-0855-47ca-a101-0519afac3c0a: 'User Result' # User Result
    ed2a03c5-bea9-4bed-8fe2-2a9e97abb03e: Team # Team
    f1be4708-798f-4906-84b1-b8c6e54a32e3: Package # Package
plugins:
  dashboard-begone:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  entry-gps-coordinates:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  incognito-field:
    edition: standard
    enabled: true
    schemaVersion: 1.1.1
  preparse-field:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.5
    settings: null
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  related:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      allowedCategories:
        - taskbookGroups
      allowedSections:
        - nobodyIsGoingToCallASectionThis
  reverserelations:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  sp:
    edition: standard
    enabled: true
    schemaVersion: 0.0.1
  super-table:
    enabled: '1'
    licenseKey: null
    schemaVersion: 2.2.1
    settings: null
  wordsmith:
    edition: standard
    enabled: true
    schemaVersion: 0.0.0.0
system:
  edition: pro
  live: true
  name: 'Skills Plus'
  schemaVersion: 3.7.7
  timeZone: UTC
