defaultPlacement: end
fieldLayouts:
  af614df0-8160-4a85-9005-ec5b4a45a7ed:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: bfce8aaa-028f-4d73-8f1d-20ba8f5a871b # Column Layout
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6b431a5f-e1ee-4520-ab30-89ca72993c00 # Heading
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c3c65d33-35c6-416d-9e88-c5a678f09161 # Include Add Achievement? 
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 48909e73-b939-470f-b472-53ee709db6e4 # Module Group Read Only
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fb5bee58-9ee4-4a57-b03f-59c886c40cad # Module Group Menu
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b3bb5932-8ec6-48a5-af26-7d974a69e57a # Auto Endorse?
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1d522b30-9aa0-4fc8-afd1-84e738233479 # Certificate
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 1
      -
        elements:
          -
            fieldUid: a1f70b85-8550-4cf0-87a5-1f16cde82405 # Taskbooks
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: da81a368-f84c-47f8-9e3a-b83346be0865 # Module Group Minimum Optional
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 680431de-8445-48e9-8acf-e32d867f73dd # Module Group Costs
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e427fbb1-c8bc-4ad3-9913-e5c7931d63f2 # Module Group Max Cost
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 294cd8d8-83ae-4d68-a8b1-5acd3d3f6ca3 # Module Group Single Cost
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5bdda926-785f-4d89-aebe-9a805b3dab29 # Module Group Resit Cost
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: dbbf1f49-3b86-4c6d-aa5a-4170483a35f1 # User Role
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Taskbooks
        sortOrder: 2
      -
        elements:
          -
            fieldUid: e510ee00-626f-454c-8022-6f855080c882 # All Companies
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f2e34bbd-dc9f-4253-90fc-178dc6742141 # Companies
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Company Results'
        sortOrder: 3
handle: moduleGroups
name: 'Module Groups'
siteSettings:
  47b102e1-4aed-4206-8420-dfd6e6684f7c: # Skills Plus (en-GB)
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 2
  uid: bc778126-df63-4aaa-98b1-a3cbd027192f
