defaultPlacement: end
fieldLayouts:
  af614df0-8160-4a85-9005-ec5b4a45a7ed:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 8f67f88f-ec6b-4e49-9a91-d18d903b5066
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 6b431a5f-e1ee-4520-ab30-89ca72993c00 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 57790bba-d887-4d93-b1d4-498aad2c32c8
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: c3c65d33-35c6-416d-9e88-c5a678f09161 # Include Add Achievement? 
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 622c1df0-cebd-45ce-ba2b-8ba677ae4242
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 48909e73-b939-470f-b472-53ee709db6e4 # Module Group Read Only
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 566424ac-0485-4e89-b16e-b4bf83600e08
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: b3bb5932-8ec6-48a5-af26-7d974a69e57a # Auto Endorse?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4b23c3a2-7346-41b4-86fb-e4ce14c478e7
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 1d522b30-9aa0-4fc8-afd1-84e738233479 # Certificate
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9da51702-a70f-465d-bd55-110b61662a3c
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 56d59169-060f-4069-b7e9-b4b71c9d6b80
            userCondition: null
          -
            elementCondition: null
            fieldUid: a14afbef-0a93-407a-92e5-5cae1d2ecb1e # Module Group Visibility
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 007bf793-016b-42da-aade-ac0c629a3253
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: fb5bee58-9ee4-4a57-b03f-59c886c40cad # Module Group Menu
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7ac2c3a9-e47f-48c0-912d-0efda1357139
            userCondition: null
            warning: null
            width: 50
        name: Settings
        uid: 6fb0be62-1612-4320-9fec-959905d491ef
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: bfce8aaa-028f-4d73-8f1d-20ba8f5a871b # Column Layout
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 74b471b0-0207-4a19-8661-54b10984f208
            userCondition: null
            warning: null
            width: 100
        name: 'Column Layout'
        uid: 7ee45822-6c48-47b5-a49e-3ede294d5288
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e510ee00-626f-454c-8022-6f855080c882 # All Companies
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6ca8515b-50ec-41d9-96ba-231aa0b6afe2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f2e34bbd-dc9f-4253-90fc-178dc6742141 # Companies
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aa585289-816b-4804-b138-9aaf766cf9bf
            userCondition: null
            warning: null
            width: 100
        name: 'Company Results'
        uid: 05e543a0-1e3f-4c99-9395-c91e84a620bc
        userCondition: null
handle: moduleGroups
name: 'Module Groups'
siteSettings:
  47b102e1-4aed-4206-8420-dfd6e6684f7c: # Skills Plus (en-GB)
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 2
  uid: bc778126-df63-4aaa-98b1-a3cbd027192f
