defaultPlacement: end
fieldLayouts:
  6b497f1f-cd55-4082-9ba0-463e8dd5acfc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: Type
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 72ea42c1-14de-4122-80b4-fb60fde06e83
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dba3c960-8963-4b09-810f-2b7bf1b3ab77 # Product Result Custom Fields
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f65b72ff-9c5c-48c6-8fe3-4fc8e52a1caa
            userCondition: null
            warning: null
            width: 100
        name: 'Product Type'
        uid: 0e619a25-1b66-4e03-8aa7-70dce1eee2e6
        userCondition: null
handle: productTypes
name: 'Product Types'
siteSettings:
  47b102e1-4aed-4206-8420-dfd6e6684f7c: # Skills Plus (en-GB)
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 7bc535aa-9db7-42ed-9c9d-4a68890fe31b
