defaultPlacement: end
fieldLayouts:
  6b497f1f-cd55-4082-9ba0-463e8dd5acfc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: Type
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 8d600949-7553-483a-95a5-f3994e57eed2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dba3c960-8963-4b09-810f-2b7bf1b3ab77 # Product Result Custom Fields
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 42b2a0f6-e748-4679-a7c9-3510dbdd8d95
            userCondition: null
            warning: null
            width: 100
        name: 'Product Type'
        uid: 80adf626-3f49-4ea0-bd48-48065b27541e
        userCondition: null
handle: productTypes
name: 'Product Types'
siteSettings:
  47b102e1-4aed-4206-8420-dfd6e6684f7c: # Skills Plus (en-GB)
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 7bc535aa-9db7-42ed-9c9d-4a68890fe31b
