defaultPlacement: end
fieldLayouts:
  6b497f1f-cd55-4082-9ba0-463e8dd5acfc:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: ''
            label: Type
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: 'Product Type'
        sortOrder: 1
handle: productTypes
name: 'Product Types'
siteSettings:
  47b102e1-4aed-4206-8420-dfd6e6684f7c: # Skills Plus (en-GB)
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 7bc535aa-9db7-42ed-9c9d-4a68890fe31b
