defaultPlacement: end
fieldLayouts:
  33adba6b-22c9-44dc-9937-48757ba24cf2:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: 09dd9f6b-4143-4e66-adc3-f156a34cdfe0 # Reviewer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 0b7c55cd-d5b0-44f1-ba0a-882e155ae4bf # External
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 585cec7d-218d-4241-a113-0a7ab6f7503e # Dashboard
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
        name: 'Job Role'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 32a14957-b145-4e24-9ac6-6e70cb4dd5fd # Role Module Count
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: eafc63ea-2bd3-4998-9ce8-c8fd129bbe1b # Role Unit Count
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 5d67e162-9058-47ba-aa41-a025b21fce64 # Linked Data
            instructions: ''
            label: __blank__
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Data
        sortOrder: 2
      -
        elements:
          -
            fieldUid: dc88c84b-17f2-4b8b-8cc6-124b5115c9cc # Legacy ID
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 440ee4d2-9c90-47a0-a2e7-9ec4d1a97683 # Data Imported
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Legacy
        sortOrder: 3
handle: roles
name: 'Job Roles'
siteSettings:
  47b102e1-4aed-4206-8420-dfd6e6684f7c: # Skills Plus (en-GB)
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: cddeab59-d20c-4b6e-80e2-3912183a9657
