defaultPlacement: end
fieldLayouts:
  33adba6b-22c9-44dc-9937-48757ba24cf2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 63ca276f-4c6d-4db5-b781-464a6dfeae8e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 09dd9f6b-4143-4e66-adc3-f156a34cdfe0 # Reviewer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 00dfd239-faa6-4107-af22-10e7dfa37fd6
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 0b7c55cd-d5b0-44f1-ba0a-882e155ae4bf # External
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 24e02595-028f-455c-ac9c-25d36df32454
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 585cec7d-218d-4241-a113-0a7ab6f7503e # Dashboard
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ce6e7ef6-ca9e-49b5-9f8c-c4cb3adc3bef
            userCondition: null
            warning: null
            width: 25
        name: 'Job Role'
        uid: 56dc2ffe-a6e2-4e57-a029-18d3e0aa22b7
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 32a14957-b145-4e24-9ac6-6e70cb4dd5fd # Role Module Count
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3099b3b6-3d20-4380-86e9-6646bba8a8be
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: eafc63ea-2bd3-4998-9ce8-c8fd129bbe1b # Role Unit Count
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 54852e37-2bf1-4c5d-a76f-e1f60d6c2efc
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 5d67e162-9058-47ba-aa41-a025b21fce64 # Linked Data
            instructions: null
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d27d8eda-5d55-4b6a-8ec4-0f9245d2b679
            userCondition: null
            warning: null
            width: 100
        name: Data
        uid: 364fc565-5d5a-4d7f-b2f9-9d098fce9787
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: dc88c84b-17f2-4b8b-8cc6-124b5115c9cc # Legacy ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 37defc24-33f2-4d90-86e8-4aa69a7f3e85
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 440ee4d2-9c90-47a0-a2e7-9ec4d1a97683 # Data Imported
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1fe6283f-2ec6-4352-a813-fe81695e3ec2
            userCondition: null
            warning: null
            width: 50
        name: Legacy
        uid: ccea7dd4-fa6d-4ad2-b4ed-7ecd28f5a979
        userCondition: null
handle: roles
name: 'Job Roles'
siteSettings:
  47b102e1-4aed-4206-8420-dfd6e6684f7c: # Skills Plus (en-GB)
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: cddeab59-d20c-4b6e-80e2-3912183a9657
