fieldLayouts:
  a33c5200-627f-4920-a685-580ea708b281:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 161a5358-424c-41a6-89dd-035186a098df
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7a30ed32-ad2f-46d8-8481-466e532307b6
        userCondition: null
handle: default
name: Default
