fieldLayouts:
  a33c5200-627f-4920-a685-580ea708b281:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: e593a012-8b9e-4c28-b3a6-1a98d797d962
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ce38142e-9474-4be4-9b92-9d985ff2929f
        userCondition: null
handle: default
name: Default
