description: null
handle: usersTaskbookPending
name: 'Users [Taskbook Pending]'
permissions:
  - 'createentries:0c63d248-a060-4ecd-b881-00607c9f4024' # Taskbook Packages
  - 'viewentries:0c63d248-a060-4ecd-b881-00607c9f4024' # Taskbook Packages
  - 'saveentries:0c63d248-a060-4ecd-b881-00607c9f4024' # Taskbook Packages
