#!/bin/bash

# domains i.e. folders (separated by space)
DOMAINS="bcsa bics cha demo demo1 demo2 demo3 demo4 demo5 eoc iopf ltp poultec poultrypassport ptr"
F=$1
URI="/actions/lantra/cron/run?frequency=$F"

for DOMAIN in $DOMAINS;
do
        # production
        RESPONSE=$(curl --silent $DOMAIN.skills-plus.net$URI)
        echo "$F cron run for $DOMAIN on PROD"
        echo $RESPONSE

        # uat
        RESPONSE=$(curl --silent $DOMAIN.newuat.skills-plus.net$URI)
        echo "$F cron run for $DOMAIN on UAT"
        echo $RESPONSE
done


#!/bin/bash

DOMAIN="bcsa"
F=$1
URI="/actions/lantra/cron/run?frequency=$F"

# production
RESPONSE=$(curl --silent $DOMAIN.skills-plus.net$URI)
echo "$F cron run for $DOMAIN on PROD"
echo $RESPONSE