#!/bin/bash

# make sure we have input
if [[ $# -eq 0 ]] ; then
    echo 'You must enter site parameters i.e. craft3 bics'
    exit 0
fi

SITE="$1"

REMOTE_IP="10.1.4.4"
REMOTE_FOLDER="/datadisk/sites/$SITE"

# set temp directory
TMP_DIR="/git/tmp/craft3"
mkdir -p $TMP_DIR
git --work-tree=$TMP_DIR --git-dir="/git/cpd.git" checkout -f craft3

if [[ "$2" == "" ]] ; then
    # install composer
    cd $TMP_DIR/craft3/craft
    composer install --no-suggest
fi

# copy .env to project
cp /git/config/.env $TMP_DIR/craft3/craft

## START COPY ##

# set .env properties
echo "ENVIRONMENT='dev'" >> $TMP_DIR/craft3/craft/.env
echo "SITE='${SITE}'" >> $TMP_DIR/craft3/craft/.env

# switch directory ownership back to git
ssh git@$REMOTE_IP sudo chown -R git:apache $REMOTE_FOLDER

# copy files
rsync -acvz --no-perms --no-owner --no-group --no-times $TMP_DIR/craft3/craft git@$REMOTE_IP:$REMOTE_FOLDER
rsync -acvz --no-perms --no-owner --no-group --no-times $TMP_DIR/craft3/html git@$REMOTE_IP:$REMOTE_FOLDER

# copy skills-plus repo
rsync -acvz --no-perms --no-owner --no-group --no-times $TMP_DIR/craft3/src/repository git@$REMOTE_IP:$REMOTE_FOLDER/src/

# switch directory ownership back to apache
ssh git@$REMOTE_IP sudo chown -R apache:apache $REMOTE_FOLDER

# set file and folder permissions
ssh git@$REMOTE_IP sudo chmod 744 $REMOTE_FOLDER/craft/.env
ssh git@$REMOTE_IP sudo chmod -R 744 $REMOTE_FOLDER/craft/storage
ssh git@$REMOTE_IP sudo chmod 744 $REMOTE_FOLDER/craft/composer.json
ssh git@$REMOTE_IP sudo chmod 744 $REMOTE_FOLDER/craft/composer.lock
ssh git@$REMOTE_IP sudo chmod 744 $REMOTE_FOLDER/craft/config/license.key
ssh git@$REMOTE_IP sudo chmod -R 744 $REMOTE_FOLDER/craft/vendor
ssh git@$REMOTE_IP sudo chmod -R 744 $REMOTE_FOLDER/html/cpresources

# update craft via cli
ssh git@$REMOTE_IP sudo chmod a+x $REMOTE_FOLDER/craft/craft
ssh git@$REMOTE_IP sudo $REMOTE_FOLDER/craft/./craft project-config/sync
ssh git@$REMOTE_IP sudo $REMOTE_FOLDER/craft/./craft migrate/all

## END COPY ##

# remove temp files
rm -rf "$TMP_DIR"
